'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.2.97:8686/AutentificadorMob.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_AutentificadorReference_AutentificadorMob() As String
            Get
                Return CType(Me("UAUMobileWebAPI_AutentificadorReference_AutentificadorMob"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.2.97:8686/WebServices/wsMobile.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsMobileReference_wsMobile() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsMobileReference_wsMobile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:10730/webservices/wsnovidade.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsNovidadeReference_wsNovidade() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsNovidadeReference_wsNovidade"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/Webservices/ProcessoPagamento.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_ProcessoPagamentoReference_ProcessoPagamento() As String
            Get
                Return CType(Me("UAUMobileWebAPI_ProcessoPagamentoReference_ProcessoPagamento"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/WebServices/boleto.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_BoletoReference_BoletoServices() As String
            Get
                Return CType(Me("UAUMobileWebAPI_BoletoReference_BoletoServices"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/Webservices/wsConfigGerais.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsConfigGerais_wsConfigGerais() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsConfigGerais_wsConfigGerais"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8282/WsEmpresa.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsEmpresaReference_WsEmpresa() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsEmpresaReference_WsEmpresa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.uau.com.br/webservices/wsregistrouau.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsEmpresaProdReference_wsRegistroUau() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsEmpresaProdReference_wsRegistroUau"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8686/Webservices/wsMedicao.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsMedicaoReference_wsMedicao() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsMedicaoReference_wsMedicao"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/Webservices/pessoas.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsPessoasReference_Pessoas() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsPessoasReference_Pessoas"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/webservices/wsUsuarios.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsUsuariosReference_wsUsuarios() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsUsuariosReference_wsUsuarios"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/Webservices/seguranca.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_segurancaReference_Seguranca() As String
            Get
                Return CType(Me("UAUMobileWebAPI_segurancaReference_Seguranca"),String)
            End Get
        End Property
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/Webservices/WsCotacao.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsCotacaoReference_WsCotacao() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsCotacaoReference_WsCotacao"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:3016/Webservices/WsHistoricoInsumo.asmx")>  _
        Public ReadOnly Property UAUMobileWebAPI_wsHistoricoInsumoReference_wsHistoricoInsumo() As String
            Get
                Return CType(Me("UAUMobileWebAPI_wsHistoricoInsumoReference_wsHistoricoInsumo"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.UAUMobileWebAPI.My.MySettings
            Get
                Return Global.UAUMobileWebAPI.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
