'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CamposPersonConfEspelho
    Public Property Codigo_cpce As Integer
    Public Property CodigoCfg_cpce As Integer
    Public Property NumEmp_cpce As Integer
    Public Property Descricao_cpce As String
    Public Property NomeCampo_cpce As String
    Public Property Ordem_cpce As Nullable(Of Short)
    Public Property TipoFormatacao_cpce As String
    Public Property TamanhoFormatacao_cpce As Nullable(Of Integer)

End Class
