'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfPortalUAU
    Public Property NumEmp_PWeb As Integer
    Public Property DescrPortalUAU_PWeb As String
    Public Property URLWS_PWeb As String
    Public Property EmailContato_PWeb As String
    Public Property EmpresaUAU_PWeb As Nullable(Of Short)
    Public Property ObraUAU_PWeb As String
    Public Property UsrCad_PWeb As String
    Public Property DataCad_Pweb As Nullable(Of Date)
    Public Property DataAlt_Pweb As Nullable(Of Date)
    Public Property UsrAlt_PWeb As String
    Public Property AtInat_PWeb As Nullable(Of Short)
    Public Property HTML_PWeb As String
    Public Property URLPaginaCentro_Pweb As String
    Public Property NomeContato_PWeb As String
    Public Property Telefone_PWeb As String
    Public Property UsrLoginUAU_PWeb As String

    Public Overridable Property ConfCadProposta As ConfCadProposta

End Class
