'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfigIRPFParcela
    Public Property NumEmp_cip As Integer
    Public Property TipoParc_cip As String
    Public Property DescricaoParc_cip As String

End Class
