'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfCadUsuario
    Public Property NumEmp_ccu As Integer
    Public Property AutoManual_ccu As Boolean
    Public Property AtualizaEmail_ccu As Boolean
    Public Property AutoCadastro_ccu As Boolean
    Public Property ConfirmaCadEmail_ccu As Boolean

End Class
