'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfEspelho
    Public Property Codigo_cfg As Integer
    Public Property NumEmp_cfg As Integer
    Public Property Descr_cfg As String
    Public Property QtdeColuna_cfg As Nullable(Of Integer)

    Public Overridable Property ItensConfEspelho As ICollection(Of ItensConfEspelho) = New HashSet(Of ItensConfEspelho)
    Public Overridable Property StatusPersonConfEspelho As ICollection(Of StatusPersonConfEspelho) = New HashSet(Of StatusPersonConfEspelho)

End Class
