'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfGeralEmpresa
    Public Property NumEmp_cge As Integer
    Public Property Configuracao_cge As String
    Public Property Valor_cge As String

End Class
