'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfServico
    Public Property NumEmp_cs As Integer
    Public Property MostrarDemonsPagtoCli_cs As Boolean
    Public Property MostrarReimpBoleto_cs As Boolean
    Public Property HabilitarAnexos_cs As Boolean
    Public Property MostrarCadTerrenos_cs As Boolean
    Public Property BoletoAntecipado_cs As Boolean
    Public Property InadimplenteGeraBol_cs As Boolean

End Class
