'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfCadProposta
    Public Property NumEmp_CProp As Integer
    Public Property MostrarDetComissao_Cprop As Boolean
    Public Property ResumoContratual_Cprop As String

    Public Overridable Property ConfPortalUAU As ConfPortalUAU

End Class
