'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ItensConfEspelho
    Public Property CodigoCfg_itc As Integer
    Public Property Codigo_itc As Integer
    Public Property Empresa_itc As Integer
    Public Property Obra_itc As String
    Public Property Produto_itc As String
    Public Property NumEmp_itc As Integer

    Public Overridable Property ConfEspelho As ConfEspelho

End Class
