'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StatusPersonConfEspelho
    Public Property CodigoCfg_spce As Integer
    Public Property NumEmp_spce As Integer
    Public Property Status_spce As Integer

    Public Overridable Property ConfEspelho As ConfEspelho

End Class
