'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class UauWebBDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UauWebBDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CamposPersonConfEspelho() As DbSet(Of CamposPersonConfEspelho)
    Public Overridable Property ConfCadProposta() As DbSet(Of ConfCadProposta)
    Public Overridable Property ConfCadUsuario() As DbSet(Of ConfCadUsuario)
    Public Overridable Property ConfEspelho() As DbSet(Of ConfEspelho)
    Public Overridable Property ConfGeralEmpresa() As DbSet(Of ConfGeralEmpresa)
    Public Overridable Property ConfigIRPFParcela() As DbSet(Of ConfigIRPFParcela)
    Public Overridable Property ConfPortalUAU() As DbSet(Of ConfPortalUAU)
    Public Overridable Property ConfReimpBoleto() As DbSet(Of ConfReimpBoleto)
    Public Overridable Property ConfServico() As DbSet(Of ConfServico)
    Public Overridable Property ExtratoCliente() As DbSet(Of ExtratoCliente)
    Public Overridable Property ExtratoMensagem() As DbSet(Of ExtratoMensagem)
    Public Overridable Property ExtratoParcela() As DbSet(Of ExtratoParcela)
    Public Overridable Property ItensConfEspelho() As DbSet(Of ItensConfEspelho)
    Public Overridable Property StatusPersonConfEspelho() As DbSet(Of StatusPersonConfEspelho)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)

End Class
