'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace BoletoReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BoletoServicesSoap", [Namespace]:="http://tempuri.org/PortalUAU_WS/BoletoServices")>  _
    Partial Public Class BoletoServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarBoletosDoClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarBoletosDoClienteMobOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarDadosDoBoletoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObterCodigoDeBarrasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObterLinhaDigitavelOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObterMensagemDoBoletoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarBoletosReimpressaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GerarBoletoDoBancoCorrespondenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObterQtdTitularOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObterNomeSacadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_BoletoReference_BoletoServices
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarBoletosDoClienteCompleted As ConsultarBoletosDoClienteCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarBoletosDoClienteMobCompleted As ConsultarBoletosDoClienteMobCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarDadosDoBoletoCompleted As ConsultarDadosDoBoletoCompletedEventHandler
        
        '''<remarks/>
        Public Event ObterCodigoDeBarrasCompleted As ObterCodigoDeBarrasCompletedEventHandler
        
        '''<remarks/>
        Public Event ObterLinhaDigitavelCompleted As ObterLinhaDigitavelCompletedEventHandler
        
        '''<remarks/>
        Public Event ObterMensagemDoBoletoCompleted As ObterMensagemDoBoletoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarBoletosReimpressaoCompleted As ConsultarBoletosReimpressaoCompletedEventHandler
        
        '''<remarks/>
        Public Event GerarBoletoDoBancoCorrespondenteCompleted As GerarBoletoDoBancoCorrespondenteCompletedEventHandler
        
        '''<remarks/>
        Public Event ObterQtdTitularCompleted As ObterQtdTitularCompletedEventHandler
        
        '''<remarks/>
        Public Event ObterNomeSacadoCompleted As ObterNomeSacadoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ConsultarBoletosDoCliente", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarBoletosDoCliente(ByVal codPessoa As Integer, ByVal naoMostraBoletoVencido As Boolean, ByVal usuario As String, ByVal tipoUsuario As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarBoletosDoCliente", New Object() {codPessoa, naoMostraBoletoVencido, usuario, tipoUsuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarBoletosDoClienteAsync(ByVal codPessoa As Integer, ByVal naoMostraBoletoVencido As Boolean, ByVal usuario As String, ByVal tipoUsuario As Integer)
            Me.ConsultarBoletosDoClienteAsync(codPessoa, naoMostraBoletoVencido, usuario, tipoUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarBoletosDoClienteAsync(ByVal codPessoa As Integer, ByVal naoMostraBoletoVencido As Boolean, ByVal usuario As String, ByVal tipoUsuario As Integer, ByVal userState As Object)
            If (Me.ConsultarBoletosDoClienteOperationCompleted Is Nothing) Then
                Me.ConsultarBoletosDoClienteOperationCompleted = AddressOf Me.OnConsultarBoletosDoClienteOperationCompleted
            End If
            Me.InvokeAsync("ConsultarBoletosDoCliente", New Object() {codPessoa, naoMostraBoletoVencido, usuario, tipoUsuario}, Me.ConsultarBoletosDoClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarBoletosDoClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarBoletosDoClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarBoletosDoClienteCompleted(Me, New ConsultarBoletosDoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ConsultarBoletosDoClienteMob", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarBoletosDoClienteMob(ByVal codPessoa As Integer, ByVal naoMostraBoletoVencido As Boolean, ByVal usuario As String, ByVal tipoUsuario As Integer, ByVal limit As Integer, ByVal whereClausule As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarBoletosDoClienteMob", New Object() {codPessoa, naoMostraBoletoVencido, usuario, tipoUsuario, limit, whereClausule})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarBoletosDoClienteMobAsync(ByVal codPessoa As Integer, ByVal naoMostraBoletoVencido As Boolean, ByVal usuario As String, ByVal tipoUsuario As Integer, ByVal limit As Integer, ByVal whereClausule As String)
            Me.ConsultarBoletosDoClienteMobAsync(codPessoa, naoMostraBoletoVencido, usuario, tipoUsuario, limit, whereClausule, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarBoletosDoClienteMobAsync(ByVal codPessoa As Integer, ByVal naoMostraBoletoVencido As Boolean, ByVal usuario As String, ByVal tipoUsuario As Integer, ByVal limit As Integer, ByVal whereClausule As String, ByVal userState As Object)
            If (Me.ConsultarBoletosDoClienteMobOperationCompleted Is Nothing) Then
                Me.ConsultarBoletosDoClienteMobOperationCompleted = AddressOf Me.OnConsultarBoletosDoClienteMobOperationCompleted
            End If
            Me.InvokeAsync("ConsultarBoletosDoClienteMob", New Object() {codPessoa, naoMostraBoletoVencido, usuario, tipoUsuario, limit, whereClausule}, Me.ConsultarBoletosDoClienteMobOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarBoletosDoClienteMobOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarBoletosDoClienteMobCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarBoletosDoClienteMobCompleted(Me, New ConsultarBoletosDoClienteMobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ConsultarDadosDoBoleto", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarDadosDoBoleto(ByVal banco As String, ByVal seuNumero As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarDadosDoBoleto", New Object() {banco, seuNumero})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarDadosDoBoletoAsync(ByVal banco As String, ByVal seuNumero As String)
            Me.ConsultarDadosDoBoletoAsync(banco, seuNumero, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarDadosDoBoletoAsync(ByVal banco As String, ByVal seuNumero As String, ByVal userState As Object)
            If (Me.ConsultarDadosDoBoletoOperationCompleted Is Nothing) Then
                Me.ConsultarDadosDoBoletoOperationCompleted = AddressOf Me.OnConsultarDadosDoBoletoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarDadosDoBoleto", New Object() {banco, seuNumero}, Me.ConsultarDadosDoBoletoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarDadosDoBoletoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarDadosDoBoletoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarDadosDoBoletoCompleted(Me, New ConsultarDadosDoBoletoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ObterCodigoDeBarras", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterCodigoDeBarras(ByVal banco As String, ByVal dataVenc As Date, ByVal valorNominal As Double, ByVal campoLivre As String) As String
            Dim results() As Object = Me.Invoke("ObterCodigoDeBarras", New Object() {banco, dataVenc, valorNominal, campoLivre})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObterCodigoDeBarrasAsync(ByVal banco As String, ByVal dataVenc As Date, ByVal valorNominal As Double, ByVal campoLivre As String)
            Me.ObterCodigoDeBarrasAsync(banco, dataVenc, valorNominal, campoLivre, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObterCodigoDeBarrasAsync(ByVal banco As String, ByVal dataVenc As Date, ByVal valorNominal As Double, ByVal campoLivre As String, ByVal userState As Object)
            If (Me.ObterCodigoDeBarrasOperationCompleted Is Nothing) Then
                Me.ObterCodigoDeBarrasOperationCompleted = AddressOf Me.OnObterCodigoDeBarrasOperationCompleted
            End If
            Me.InvokeAsync("ObterCodigoDeBarras", New Object() {banco, dataVenc, valorNominal, campoLivre}, Me.ObterCodigoDeBarrasOperationCompleted, userState)
        End Sub
        
        Private Sub OnObterCodigoDeBarrasOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObterCodigoDeBarrasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObterCodigoDeBarrasCompleted(Me, New ObterCodigoDeBarrasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ObterLinhaDigitavel", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterLinhaDigitavel(ByVal codigoDeBarras As String) As String
            Dim results() As Object = Me.Invoke("ObterLinhaDigitavel", New Object() {codigoDeBarras})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObterLinhaDigitavelAsync(ByVal codigoDeBarras As String)
            Me.ObterLinhaDigitavelAsync(codigoDeBarras, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObterLinhaDigitavelAsync(ByVal codigoDeBarras As String, ByVal userState As Object)
            If (Me.ObterLinhaDigitavelOperationCompleted Is Nothing) Then
                Me.ObterLinhaDigitavelOperationCompleted = AddressOf Me.OnObterLinhaDigitavelOperationCompleted
            End If
            Me.InvokeAsync("ObterLinhaDigitavel", New Object() {codigoDeBarras}, Me.ObterLinhaDigitavelOperationCompleted, userState)
        End Sub
        
        Private Sub OnObterLinhaDigitavelOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObterLinhaDigitavelCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObterLinhaDigitavelCompleted(Me, New ObterLinhaDigitavelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ObterMensagemDoBoleto", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterMensagemDoBoleto(ByVal seuNumero As Integer, ByVal banco As Short, ByVal codEmpresa As Short, ByVal instrucao As String, ByVal carteira As String) As String
            Dim results() As Object = Me.Invoke("ObterMensagemDoBoleto", New Object() {seuNumero, banco, codEmpresa, instrucao, carteira})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObterMensagemDoBoletoAsync(ByVal seuNumero As Integer, ByVal banco As Short, ByVal codEmpresa As Short, ByVal instrucao As String, ByVal carteira As String)
            Me.ObterMensagemDoBoletoAsync(seuNumero, banco, codEmpresa, instrucao, carteira, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObterMensagemDoBoletoAsync(ByVal seuNumero As Integer, ByVal banco As Short, ByVal codEmpresa As Short, ByVal instrucao As String, ByVal carteira As String, ByVal userState As Object)
            If (Me.ObterMensagemDoBoletoOperationCompleted Is Nothing) Then
                Me.ObterMensagemDoBoletoOperationCompleted = AddressOf Me.OnObterMensagemDoBoletoOperationCompleted
            End If
            Me.InvokeAsync("ObterMensagemDoBoleto", New Object() {seuNumero, banco, codEmpresa, instrucao, carteira}, Me.ObterMensagemDoBoletoOperationCompleted, userState)
        End Sub
        
        Private Sub OnObterMensagemDoBoletoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObterMensagemDoBoletoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObterMensagemDoBoletoCompleted(Me, New ObterMensagemDoBoletoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ConsultarBoletosReimpressao", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarBoletosReimpressao(ByVal intEmpresa As Integer, ByVal strObra As String, ByVal intNumVenda As Integer, ByVal blnNaoMostraBoletoVencido As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarBoletosReimpressao", New Object() {intEmpresa, strObra, intNumVenda, blnNaoMostraBoletoVencido})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarBoletosReimpressaoAsync(ByVal intEmpresa As Integer, ByVal strObra As String, ByVal intNumVenda As Integer, ByVal blnNaoMostraBoletoVencido As Boolean)
            Me.ConsultarBoletosReimpressaoAsync(intEmpresa, strObra, intNumVenda, blnNaoMostraBoletoVencido, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarBoletosReimpressaoAsync(ByVal intEmpresa As Integer, ByVal strObra As String, ByVal intNumVenda As Integer, ByVal blnNaoMostraBoletoVencido As Boolean, ByVal userState As Object)
            If (Me.ConsultarBoletosReimpressaoOperationCompleted Is Nothing) Then
                Me.ConsultarBoletosReimpressaoOperationCompleted = AddressOf Me.OnConsultarBoletosReimpressaoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarBoletosReimpressao", New Object() {intEmpresa, strObra, intNumVenda, blnNaoMostraBoletoVencido}, Me.ConsultarBoletosReimpressaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarBoletosReimpressaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarBoletosReimpressaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarBoletosReimpressaoCompleted(Me, New ConsultarBoletosReimpressaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/GerarBoletoDoBancoCorrespondente", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GerarBoletoDoBancoCorrespondente(ByVal identBanco As String, ByVal digBanco As String, ByVal logoBanco As String, ByVal cedenteBanco As String, ByVal campoLivre As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GerarBoletoDoBancoCorrespondente", New Object() {identBanco, digBanco, logoBanco, cedenteBanco, campoLivre})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GerarBoletoDoBancoCorrespondenteAsync(ByVal identBanco As String, ByVal digBanco As String, ByVal logoBanco As String, ByVal cedenteBanco As String, ByVal campoLivre As String)
            Me.GerarBoletoDoBancoCorrespondenteAsync(identBanco, digBanco, logoBanco, cedenteBanco, campoLivre, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GerarBoletoDoBancoCorrespondenteAsync(ByVal identBanco As String, ByVal digBanco As String, ByVal logoBanco As String, ByVal cedenteBanco As String, ByVal campoLivre As String, ByVal userState As Object)
            If (Me.GerarBoletoDoBancoCorrespondenteOperationCompleted Is Nothing) Then
                Me.GerarBoletoDoBancoCorrespondenteOperationCompleted = AddressOf Me.OnGerarBoletoDoBancoCorrespondenteOperationCompleted
            End If
            Me.InvokeAsync("GerarBoletoDoBancoCorrespondente", New Object() {identBanco, digBanco, logoBanco, cedenteBanco, campoLivre}, Me.GerarBoletoDoBancoCorrespondenteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGerarBoletoDoBancoCorrespondenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GerarBoletoDoBancoCorrespondenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GerarBoletoDoBancoCorrespondenteCompleted(Me, New GerarBoletoDoBancoCorrespondenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ObterQtdTitular", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterQtdTitular(ByVal banco As String, ByVal seuNumero As String) As Integer
            Dim results() As Object = Me.Invoke("ObterQtdTitular", New Object() {banco, seuNumero})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObterQtdTitularAsync(ByVal banco As String, ByVal seuNumero As String)
            Me.ObterQtdTitularAsync(banco, seuNumero, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObterQtdTitularAsync(ByVal banco As String, ByVal seuNumero As String, ByVal userState As Object)
            If (Me.ObterQtdTitularOperationCompleted Is Nothing) Then
                Me.ObterQtdTitularOperationCompleted = AddressOf Me.OnObterQtdTitularOperationCompleted
            End If
            Me.InvokeAsync("ObterQtdTitular", New Object() {banco, seuNumero}, Me.ObterQtdTitularOperationCompleted, userState)
        End Sub
        
        Private Sub OnObterQtdTitularOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObterQtdTitularCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObterQtdTitularCompleted(Me, New ObterQtdTitularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/BoletoServices/ObterNomeSacado", RequestNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/BoletoServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterNomeSacado(ByVal nomeSacado As String, ByVal qtdTitular As Integer) As String
            Dim results() As Object = Me.Invoke("ObterNomeSacado", New Object() {nomeSacado, qtdTitular})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObterNomeSacadoAsync(ByVal nomeSacado As String, ByVal qtdTitular As Integer)
            Me.ObterNomeSacadoAsync(nomeSacado, qtdTitular, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObterNomeSacadoAsync(ByVal nomeSacado As String, ByVal qtdTitular As Integer, ByVal userState As Object)
            If (Me.ObterNomeSacadoOperationCompleted Is Nothing) Then
                Me.ObterNomeSacadoOperationCompleted = AddressOf Me.OnObterNomeSacadoOperationCompleted
            End If
            Me.InvokeAsync("ObterNomeSacado", New Object() {nomeSacado, qtdTitular}, Me.ObterNomeSacadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnObterNomeSacadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObterNomeSacadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObterNomeSacadoCompleted(Me, New ObterNomeSacadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarBoletosDoClienteCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarBoletosDoClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarBoletosDoClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarBoletosDoClienteMobCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarBoletosDoClienteMobCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarBoletosDoClienteMobCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarDadosDoBoletoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarDadosDoBoletoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarDadosDoBoletoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ObterCodigoDeBarrasCompletedEventHandler(ByVal sender As Object, ByVal e As ObterCodigoDeBarrasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObterCodigoDeBarrasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ObterLinhaDigitavelCompletedEventHandler(ByVal sender As Object, ByVal e As ObterLinhaDigitavelCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObterLinhaDigitavelCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ObterMensagemDoBoletoCompletedEventHandler(ByVal sender As Object, ByVal e As ObterMensagemDoBoletoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObterMensagemDoBoletoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarBoletosReimpressaoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarBoletosReimpressaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarBoletosReimpressaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GerarBoletoDoBancoCorrespondenteCompletedEventHandler(ByVal sender As Object, ByVal e As GerarBoletoDoBancoCorrespondenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GerarBoletoDoBancoCorrespondenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ObterQtdTitularCompletedEventHandler(ByVal sender As Object, ByVal e As ObterQtdTitularCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObterQtdTitularCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ObterNomeSacadoCompletedEventHandler(ByVal sender As Object, ByVal e As ObterNomeSacadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObterNomeSacadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
