'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsUsuariosReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsUsuariosSoap", [Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResultadoExecucao)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Info))>  _
    Partial Public Class wsUsuarios
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private StatusUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarEmailRootOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GravarUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CopiarPerfilDeOutroUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecuperarUsuarioSenhaPorLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarGruposDeUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecuperarUsuarioSenhaPorEmailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarUsuariosAtivosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarUsuariosComFiltroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarUsuariosPermissaoCopiaDePerfilOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VerificaPermissaoModuloSegurancaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarDtHrLoginUsrOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaUsuarioPeloLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_wsUsuariosReference_wsUsuarios
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event StatusUsuarioCompleted As StatusUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarEmailRootCompleted As ConsultarEmailRootCompletedEventHandler
        
        '''<remarks/>
        Public Event GravarUsuarioCompleted As GravarUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event CopiarPerfilDeOutroUsuarioCompleted As CopiarPerfilDeOutroUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event RecuperarUsuarioSenhaPorLoginCompleted As RecuperarUsuarioSenhaPorLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarGruposDeUsuarioCompleted As ConsultarGruposDeUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event RecuperarUsuarioSenhaPorEmailCompleted As RecuperarUsuarioSenhaPorEmailCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarUsuariosAtivosCompleted As ConsultarUsuariosAtivosCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarUsuariosComFiltroCompleted As ConsultarUsuariosComFiltroCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarUsuariosPermissaoCopiaDePerfilCompleted As ConsultarUsuariosPermissaoCopiaDePerfilCompletedEventHandler
        
        '''<remarks/>
        Public Event VerificaPermissaoModuloSegurancaCompleted As VerificaPermissaoModuloSegurancaCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarDtHrLoginUsrCompleted As AlterarDtHrLoginUsrCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaUsuarioPeloLoginCompleted As ConsultaUsuarioPeloLoginCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/StatusUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StatusUsuario(ByVal strUsuario As String) As EnumStatusUsuario
            Dim results() As Object = Me.Invoke("StatusUsuario", New Object() {strUsuario})
            Return CType(results(0),EnumStatusUsuario)
        End Function
        
        '''<remarks/>
        Public Overloads Sub StatusUsuarioAsync(ByVal strUsuario As String)
            Me.StatusUsuarioAsync(strUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub StatusUsuarioAsync(ByVal strUsuario As String, ByVal userState As Object)
            If (Me.StatusUsuarioOperationCompleted Is Nothing) Then
                Me.StatusUsuarioOperationCompleted = AddressOf Me.OnStatusUsuarioOperationCompleted
            End If
            Me.InvokeAsync("StatusUsuario", New Object() {strUsuario}, Me.StatusUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnStatusUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.StatusUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent StatusUsuarioCompleted(Me, New StatusUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/ConsultarEmailRoot", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarEmailRoot(ByVal login As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarEmailRoot", New Object() {login})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarEmailRootAsync(ByVal login As String)
            Me.ConsultarEmailRootAsync(login, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarEmailRootAsync(ByVal login As String, ByVal userState As Object)
            If (Me.ConsultarEmailRootOperationCompleted Is Nothing) Then
                Me.ConsultarEmailRootOperationCompleted = AddressOf Me.OnConsultarEmailRootOperationCompleted
            End If
            Me.InvokeAsync("ConsultarEmailRoot", New Object() {login}, Me.ConsultarEmailRootOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarEmailRootOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarEmailRootCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarEmailRootCompleted(Me, New ConsultarEmailRootCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/GravarUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GravarUsuario(ByVal tipoAcao As AcaoRegistro, ByVal usr As Usuario) As ResultadoExecucaoUsuario
            Dim results() As Object = Me.Invoke("GravarUsuario", New Object() {tipoAcao, usr})
            Return CType(results(0),ResultadoExecucaoUsuario)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GravarUsuarioAsync(ByVal tipoAcao As AcaoRegistro, ByVal usr As Usuario)
            Me.GravarUsuarioAsync(tipoAcao, usr, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GravarUsuarioAsync(ByVal tipoAcao As AcaoRegistro, ByVal usr As Usuario, ByVal userState As Object)
            If (Me.GravarUsuarioOperationCompleted Is Nothing) Then
                Me.GravarUsuarioOperationCompleted = AddressOf Me.OnGravarUsuarioOperationCompleted
            End If
            Me.InvokeAsync("GravarUsuario", New Object() {tipoAcao, usr}, Me.GravarUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnGravarUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.GravarUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GravarUsuarioCompleted(Me, New GravarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/CopiarPerfilDeOutroUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CopiarPerfilDeOutroUsuario(ByVal usr As Usuario) As ResultadoExecucaoUsuario
            Dim results() As Object = Me.Invoke("CopiarPerfilDeOutroUsuario", New Object() {usr})
            Return CType(results(0),ResultadoExecucaoUsuario)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CopiarPerfilDeOutroUsuarioAsync(ByVal usr As Usuario)
            Me.CopiarPerfilDeOutroUsuarioAsync(usr, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CopiarPerfilDeOutroUsuarioAsync(ByVal usr As Usuario, ByVal userState As Object)
            If (Me.CopiarPerfilDeOutroUsuarioOperationCompleted Is Nothing) Then
                Me.CopiarPerfilDeOutroUsuarioOperationCompleted = AddressOf Me.OnCopiarPerfilDeOutroUsuarioOperationCompleted
            End If
            Me.InvokeAsync("CopiarPerfilDeOutroUsuario", New Object() {usr}, Me.CopiarPerfilDeOutroUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnCopiarPerfilDeOutroUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.CopiarPerfilDeOutroUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CopiarPerfilDeOutroUsuarioCompleted(Me, New CopiarPerfilDeOutroUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/RecuperarUsuarioSenhaPorLogin", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperarUsuarioSenhaPorLogin(ByVal login As String) As RetornoMetodo
            Dim results() As Object = Me.Invoke("RecuperarUsuarioSenhaPorLogin", New Object() {login})
            Return CType(results(0),RetornoMetodo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperarUsuarioSenhaPorLoginAsync(ByVal login As String)
            Me.RecuperarUsuarioSenhaPorLoginAsync(login, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperarUsuarioSenhaPorLoginAsync(ByVal login As String, ByVal userState As Object)
            If (Me.RecuperarUsuarioSenhaPorLoginOperationCompleted Is Nothing) Then
                Me.RecuperarUsuarioSenhaPorLoginOperationCompleted = AddressOf Me.OnRecuperarUsuarioSenhaPorLoginOperationCompleted
            End If
            Me.InvokeAsync("RecuperarUsuarioSenhaPorLogin", New Object() {login}, Me.RecuperarUsuarioSenhaPorLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperarUsuarioSenhaPorLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperarUsuarioSenhaPorLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperarUsuarioSenhaPorLoginCompleted(Me, New RecuperarUsuarioSenhaPorLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/ConsultarGruposDeUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarGruposDeUsuario() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarGruposDeUsuario", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarGruposDeUsuarioAsync()
            Me.ConsultarGruposDeUsuarioAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarGruposDeUsuarioAsync(ByVal userState As Object)
            If (Me.ConsultarGruposDeUsuarioOperationCompleted Is Nothing) Then
                Me.ConsultarGruposDeUsuarioOperationCompleted = AddressOf Me.OnConsultarGruposDeUsuarioOperationCompleted
            End If
            Me.InvokeAsync("ConsultarGruposDeUsuario", New Object(-1) {}, Me.ConsultarGruposDeUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarGruposDeUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarGruposDeUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarGruposDeUsuarioCompleted(Me, New ConsultarGruposDeUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/RecuperarUsuarioSenhaPorEmail", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecuperarUsuarioSenhaPorEmail(ByVal email As String) As RetornoMetodo()
            Dim results() As Object = Me.Invoke("RecuperarUsuarioSenhaPorEmail", New Object() {email})
            Return CType(results(0),RetornoMetodo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecuperarUsuarioSenhaPorEmailAsync(ByVal email As String)
            Me.RecuperarUsuarioSenhaPorEmailAsync(email, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecuperarUsuarioSenhaPorEmailAsync(ByVal email As String, ByVal userState As Object)
            If (Me.RecuperarUsuarioSenhaPorEmailOperationCompleted Is Nothing) Then
                Me.RecuperarUsuarioSenhaPorEmailOperationCompleted = AddressOf Me.OnRecuperarUsuarioSenhaPorEmailOperationCompleted
            End If
            Me.InvokeAsync("RecuperarUsuarioSenhaPorEmail", New Object() {email}, Me.RecuperarUsuarioSenhaPorEmailOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecuperarUsuarioSenhaPorEmailOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecuperarUsuarioSenhaPorEmailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecuperarUsuarioSenhaPorEmailCompleted(Me, New RecuperarUsuarioSenhaPorEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/ConsultarUsuariosAtivos", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarUsuariosAtivos(ByVal loginUsuario As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarUsuariosAtivos", New Object() {loginUsuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarUsuariosAtivosAsync(ByVal loginUsuario As String)
            Me.ConsultarUsuariosAtivosAsync(loginUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarUsuariosAtivosAsync(ByVal loginUsuario As String, ByVal userState As Object)
            If (Me.ConsultarUsuariosAtivosOperationCompleted Is Nothing) Then
                Me.ConsultarUsuariosAtivosOperationCompleted = AddressOf Me.OnConsultarUsuariosAtivosOperationCompleted
            End If
            Me.InvokeAsync("ConsultarUsuariosAtivos", New Object() {loginUsuario}, Me.ConsultarUsuariosAtivosOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarUsuariosAtivosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarUsuariosAtivosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarUsuariosAtivosCompleted(Me, New ConsultarUsuariosAtivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/ConsultarUsuariosComFiltro", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarUsuariosComFiltro(ByVal login As String, ByVal nome As String, ByVal grupo As String, ByVal status As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarUsuariosComFiltro", New Object() {login, nome, grupo, status})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarUsuariosComFiltroAsync(ByVal login As String, ByVal nome As String, ByVal grupo As String, ByVal status As Integer)
            Me.ConsultarUsuariosComFiltroAsync(login, nome, grupo, status, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarUsuariosComFiltroAsync(ByVal login As String, ByVal nome As String, ByVal grupo As String, ByVal status As Integer, ByVal userState As Object)
            If (Me.ConsultarUsuariosComFiltroOperationCompleted Is Nothing) Then
                Me.ConsultarUsuariosComFiltroOperationCompleted = AddressOf Me.OnConsultarUsuariosComFiltroOperationCompleted
            End If
            Me.InvokeAsync("ConsultarUsuariosComFiltro", New Object() {login, nome, grupo, status}, Me.ConsultarUsuariosComFiltroOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarUsuariosComFiltroOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarUsuariosComFiltroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarUsuariosComFiltroCompleted(Me, New ConsultarUsuariosComFiltroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/ConsultarUsuariosPermissaoCopiaDePerfi"& _ 
            "l", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarUsuariosPermissaoCopiaDePerfil(ByVal login As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarUsuariosPermissaoCopiaDePerfil", New Object() {login})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarUsuariosPermissaoCopiaDePerfilAsync(ByVal login As String)
            Me.ConsultarUsuariosPermissaoCopiaDePerfilAsync(login, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarUsuariosPermissaoCopiaDePerfilAsync(ByVal login As String, ByVal userState As Object)
            If (Me.ConsultarUsuariosPermissaoCopiaDePerfilOperationCompleted Is Nothing) Then
                Me.ConsultarUsuariosPermissaoCopiaDePerfilOperationCompleted = AddressOf Me.OnConsultarUsuariosPermissaoCopiaDePerfilOperationCompleted
            End If
            Me.InvokeAsync("ConsultarUsuariosPermissaoCopiaDePerfil", New Object() {login}, Me.ConsultarUsuariosPermissaoCopiaDePerfilOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarUsuariosPermissaoCopiaDePerfilOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarUsuariosPermissaoCopiaDePerfilCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarUsuariosPermissaoCopiaDePerfilCompleted(Me, New ConsultarUsuariosPermissaoCopiaDePerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/VerificaPermissaoModuloSeguranca", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerificaPermissaoModuloSeguranca(ByVal login As String) As Boolean
            Dim results() As Object = Me.Invoke("VerificaPermissaoModuloSeguranca", New Object() {login})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VerificaPermissaoModuloSegurancaAsync(ByVal login As String)
            Me.VerificaPermissaoModuloSegurancaAsync(login, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VerificaPermissaoModuloSegurancaAsync(ByVal login As String, ByVal userState As Object)
            If (Me.VerificaPermissaoModuloSegurancaOperationCompleted Is Nothing) Then
                Me.VerificaPermissaoModuloSegurancaOperationCompleted = AddressOf Me.OnVerificaPermissaoModuloSegurancaOperationCompleted
            End If
            Me.InvokeAsync("VerificaPermissaoModuloSeguranca", New Object() {login}, Me.VerificaPermissaoModuloSegurancaOperationCompleted, userState)
        End Sub
        
        Private Sub OnVerificaPermissaoModuloSegurancaOperationCompleted(ByVal arg As Object)
            If (Not (Me.VerificaPermissaoModuloSegurancaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VerificaPermissaoModuloSegurancaCompleted(Me, New VerificaPermissaoModuloSegurancaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/AlterarDtHrLoginUsr", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AlterarDtHrLoginUsr(ByVal loginUsuario As String)
            Me.Invoke("AlterarDtHrLoginUsr", New Object() {loginUsuario})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarDtHrLoginUsrAsync(ByVal loginUsuario As String)
            Me.AlterarDtHrLoginUsrAsync(loginUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarDtHrLoginUsrAsync(ByVal loginUsuario As String, ByVal userState As Object)
            If (Me.AlterarDtHrLoginUsrOperationCompleted Is Nothing) Then
                Me.AlterarDtHrLoginUsrOperationCompleted = AddressOf Me.OnAlterarDtHrLoginUsrOperationCompleted
            End If
            Me.InvokeAsync("AlterarDtHrLoginUsr", New Object() {loginUsuario}, Me.AlterarDtHrLoginUsrOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarDtHrLoginUsrOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarDtHrLoginUsrCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarDtHrLoginUsrCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/wsUsuarios/ConsultaUsuarioPeloLogin", RequestNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/wsUsuarios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaUsuarioPeloLogin(ByVal login As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaUsuarioPeloLogin", New Object() {login})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaUsuarioPeloLoginAsync(ByVal login As String)
            Me.ConsultaUsuarioPeloLoginAsync(login, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaUsuarioPeloLoginAsync(ByVal login As String, ByVal userState As Object)
            If (Me.ConsultaUsuarioPeloLoginOperationCompleted Is Nothing) Then
                Me.ConsultaUsuarioPeloLoginOperationCompleted = AddressOf Me.OnConsultaUsuarioPeloLoginOperationCompleted
            End If
            Me.InvokeAsync("ConsultaUsuarioPeloLogin", New Object() {login}, Me.ConsultaUsuarioPeloLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaUsuarioPeloLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaUsuarioPeloLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaUsuarioPeloLoginCompleted(Me, New ConsultaUsuarioPeloLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Public Enum EnumStatusUsuario
        
        '''<remarks/>
        Ativo
        
        '''<remarks/>
        Inativo
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Public Enum AcaoRegistro
        
        '''<remarks/>
        Inserir
        
        '''<remarks/>
        Alterar
        
        '''<remarks/>
        Excluir
        
        '''<remarks/>
        Cancelar
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Partial Public Class Usuario
        
        Private usrInfoField As UsuariosInfo
        
        Private loginUsrOrigemField As String
        
        Private copiaLotacaoDepartamentoField As Boolean
        
        Private copiaPermissaoUsuarioField As Boolean
        
        Private copiaConfiguracaoUsuarioField As String
        
        Private copiaPermissaoPorObraField As String
        
        Private copiaValoresAlcadaField As String
        
        Private copiaPermissaoBancoField As String
        
        Private copiaEstruturaConsField As String
        
        Private copiaECommerceField As String
        
        Private copiaPerfilField As String
        
        Private departamentoField As String
        
        Private marcouInativarUsuarioField As Boolean
        
        Private emailOriginalField As String
        
        '''<remarks/>
        Public Property UsrInfo() As UsuariosInfo
            Get
                Return Me.usrInfoField
            End Get
            Set
                Me.usrInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LoginUsrOrigem() As String
            Get
                Return Me.loginUsrOrigemField
            End Get
            Set
                Me.loginUsrOrigemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaLotacaoDepartamento() As Boolean
            Get
                Return Me.copiaLotacaoDepartamentoField
            End Get
            Set
                Me.copiaLotacaoDepartamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaPermissaoUsuario() As Boolean
            Get
                Return Me.copiaPermissaoUsuarioField
            End Get
            Set
                Me.copiaPermissaoUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaConfiguracaoUsuario() As String
            Get
                Return Me.copiaConfiguracaoUsuarioField
            End Get
            Set
                Me.copiaConfiguracaoUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaPermissaoPorObra() As String
            Get
                Return Me.copiaPermissaoPorObraField
            End Get
            Set
                Me.copiaPermissaoPorObraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaValoresAlcada() As String
            Get
                Return Me.copiaValoresAlcadaField
            End Get
            Set
                Me.copiaValoresAlcadaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaPermissaoBanco() As String
            Get
                Return Me.copiaPermissaoBancoField
            End Get
            Set
                Me.copiaPermissaoBancoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaEstruturaCons() As String
            Get
                Return Me.copiaEstruturaConsField
            End Get
            Set
                Me.copiaEstruturaConsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaECommerce() As String
            Get
                Return Me.copiaECommerceField
            End Get
            Set
                Me.copiaECommerceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CopiaPerfil() As String
            Get
                Return Me.copiaPerfilField
            End Get
            Set
                Me.copiaPerfilField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Departamento() As String
            Get
                Return Me.departamentoField
            End Get
            Set
                Me.departamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MarcouInativarUsuario() As Boolean
            Get
                Return Me.marcouInativarUsuarioField
            End Get
            Set
                Me.marcouInativarUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailOriginal() As String
            Get
                Return Me.emailOriginalField
            End Get
            Set
                Me.emailOriginalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Partial Public Class UsuariosInfo
        Inherits Info
        
        Private login_usrField As String
        
        Private nome_usrField As String
        
        Private senha_usrField As String
        
        Private status_usrField As Byte
        
        Private grupo_usrField As String
        
        Private codCompradorNet_usrField As String
        
        Private codTelefoneNet_usrField As String
        
        Private codLoginExpNet_usrField As String
        
        Private anexos_usrField As Byte
        
        Private email_usrField As String
        
        Private codPes_usrField As Integer
        
        Private representaGrupo_usrField As Byte
        
        Private loginSiteuau_usrField As String
        
        Private senhaSiteuau_usrField As String
        
        Private dataCad_usrField As Date
        
        Private dataAlt_usrField As Date
        
        Private usrCad_UsrField As String
        
        Private usrAlt_UsrField As String
        
        Private usarSeguranca_UsrField As Boolean
        
        Private representaDepartamento_usrField As Boolean
        
        Private dataLoginUau_usrField As Date
        
        '''<remarks/>
        Public Property Login_usr() As String
            Get
                Return Me.login_usrField
            End Get
            Set
                Me.login_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nome_usr() As String
            Get
                Return Me.nome_usrField
            End Get
            Set
                Me.nome_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Senha_usr() As String
            Get
                Return Me.senha_usrField
            End Get
            Set
                Me.senha_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status_usr() As Byte
            Get
                Return Me.status_usrField
            End Get
            Set
                Me.status_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Grupo_usr() As String
            Get
                Return Me.grupo_usrField
            End Get
            Set
                Me.grupo_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodCompradorNet_usr() As String
            Get
                Return Me.codCompradorNet_usrField
            End Get
            Set
                Me.codCompradorNet_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodTelefoneNet_usr() As String
            Get
                Return Me.codTelefoneNet_usrField
            End Get
            Set
                Me.codTelefoneNet_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodLoginExpNet_usr() As String
            Get
                Return Me.codLoginExpNet_usrField
            End Get
            Set
                Me.codLoginExpNet_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Anexos_usr() As Byte
            Get
                Return Me.anexos_usrField
            End Get
            Set
                Me.anexos_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email_usr() As String
            Get
                Return Me.email_usrField
            End Get
            Set
                Me.email_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodPes_usr() As Integer
            Get
                Return Me.codPes_usrField
            End Get
            Set
                Me.codPes_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RepresentaGrupo_usr() As Byte
            Get
                Return Me.representaGrupo_usrField
            End Get
            Set
                Me.representaGrupo_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LoginSiteuau_usr() As String
            Get
                Return Me.loginSiteuau_usrField
            End Get
            Set
                Me.loginSiteuau_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SenhaSiteuau_usr() As String
            Get
                Return Me.senhaSiteuau_usrField
            End Get
            Set
                Me.senhaSiteuau_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataCad_usr() As Date
            Get
                Return Me.dataCad_usrField
            End Get
            Set
                Me.dataCad_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAlt_usr() As Date
            Get
                Return Me.dataAlt_usrField
            End Get
            Set
                Me.dataAlt_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsrCad_Usr() As String
            Get
                Return Me.usrCad_UsrField
            End Get
            Set
                Me.usrCad_UsrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsrAlt_Usr() As String
            Get
                Return Me.usrAlt_UsrField
            End Get
            Set
                Me.usrAlt_UsrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsarSeguranca_Usr() As Boolean
            Get
                Return Me.usarSeguranca_UsrField
            End Get
            Set
                Me.usarSeguranca_UsrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RepresentaDepartamento_usr() As Boolean
            Get
                Return Me.representaDepartamento_usrField
            End Get
            Set
                Me.representaDepartamento_usrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataLoginUau_usr() As Date
            Get
                Return Me.dataLoginUau_usrField
            End Get
            Set
                Me.dataLoginUau_usrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(UsuariosInfo)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Partial Public Class Info
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Partial Public Class RetornoMetodo
        
        Private operacaoField As RecuperaDados
        
        Private statusField As StatusRetorno
        
        Private mensagemField As String
        
        Private usuarioField As String
        
        Private senhaField As String
        
        Private emailField As String
        
        Private infoUsuarioField As UsuariosInfo
        
        '''<remarks/>
        Public Property Operacao() As RecuperaDados
            Get
                Return Me.operacaoField
            End Get
            Set
                Me.operacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As StatusRetorno
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Senha() As String
            Get
                Return Me.senhaField
            End Get
            Set
                Me.senhaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InfoUsuario() As UsuariosInfo
            Get
                Return Me.infoUsuarioField
            End Get
            Set
                Me.infoUsuarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Public Enum RecuperaDados
        
        '''<remarks/>
        Uau
        
        '''<remarks/>
        Portal
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Public Enum StatusRetorno
        
        '''<remarks/>
        Falha
        
        '''<remarks/>
        Sucesso
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ResultadoExecucaoUsuario)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Partial Public Class ResultadoExecucao
        
        Private tipoField As TipoMensagemResultadoExecucao
        
        Private sucessoField As Boolean
        
        Private mensagemField As String
        
        Private continuaField As Boolean
        
        '''<remarks/>
        Public Property Tipo() As TipoMensagemResultadoExecucao
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sucesso() As Boolean
            Get
                Return Me.sucessoField
            End Get
            Set
                Me.sucessoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Continua() As Boolean
            Get
                Return Me.continuaField
            End Get
            Set
                Me.continuaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Public Enum TipoMensagemResultadoExecucao
        
        '''<remarks/>
        Informativa
        
        '''<remarks/>
        Confirmacao
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/wsUsuarios")>  _
    Partial Public Class ResultadoExecucaoUsuario
        Inherits ResultadoExecucao
        
        Private marcouRepresentaDepartamentoField As Boolean
        
        Private marcouRepresentaGrupoField As Boolean
        
        Private emailOriginalField As String
        
        '''<remarks/>
        Public Property MarcouRepresentaDepartamento() As Boolean
            Get
                Return Me.marcouRepresentaDepartamentoField
            End Get
            Set
                Me.marcouRepresentaDepartamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MarcouRepresentaGrupo() As Boolean
            Get
                Return Me.marcouRepresentaGrupoField
            End Get
            Set
                Me.marcouRepresentaGrupoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailOriginal() As String
            Get
                Return Me.emailOriginalField
            End Get
            Set
                Me.emailOriginalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub StatusUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As StatusUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class StatusUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EnumStatusUsuario
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EnumStatusUsuario)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarEmailRootCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarEmailRootCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarEmailRootCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GravarUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As GravarUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GravarUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoExecucaoUsuario
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoExecucaoUsuario)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub CopiarPerfilDeOutroUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As CopiarPerfilDeOutroUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CopiarPerfilDeOutroUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoExecucaoUsuario
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoExecucaoUsuario)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RecuperarUsuarioSenhaPorLoginCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperarUsuarioSenhaPorLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperarUsuarioSenhaPorLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RetornoMetodo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RetornoMetodo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarGruposDeUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarGruposDeUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarGruposDeUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RecuperarUsuarioSenhaPorEmailCompletedEventHandler(ByVal sender As Object, ByVal e As RecuperarUsuarioSenhaPorEmailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecuperarUsuarioSenhaPorEmailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RetornoMetodo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RetornoMetodo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarUsuariosAtivosCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarUsuariosAtivosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarUsuariosAtivosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarUsuariosComFiltroCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarUsuariosComFiltroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarUsuariosComFiltroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarUsuariosPermissaoCopiaDePerfilCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarUsuariosPermissaoCopiaDePerfilCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarUsuariosPermissaoCopiaDePerfilCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub VerificaPermissaoModuloSegurancaCompletedEventHandler(ByVal sender As Object, ByVal e As VerificaPermissaoModuloSegurancaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerificaPermissaoModuloSegurancaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AlterarDtHrLoginUsrCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultaUsuarioPeloLoginCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaUsuarioPeloLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaUsuarioPeloLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
