'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsMedicaoReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsMedicaoSoap", [Namespace]:="http://tempuri.org/UAUTitanium")>  _
    Partial Public Class wsMedicao
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ContaMedicoesPendentesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaMedicoesPendentesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaItensMedicoesPendentesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaAprovacaoMedicaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AprovaMedicaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidaAprovacaoMedicaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_wsMedicaoReference_wsMedicao
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ContaMedicoesPendentesCompleted As ContaMedicoesPendentesCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaMedicoesPendentesCompleted As ConsultaMedicoesPendentesCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaItensMedicoesPendentesCompleted As ConsultaItensMedicoesPendentesCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaAprovacaoMedicaoCompleted As ConsultaAprovacaoMedicaoCompletedEventHandler
        
        '''<remarks/>
        Public Event AprovaMedicaoCompleted As AprovaMedicaoCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidaAprovacaoMedicaoCompleted As ValidaAprovacaoMedicaoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/ContaMedicoesPendentes", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ContaMedicoesPendentes(ByVal Usuario As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ContaMedicoesPendentes", New Object() {Usuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ContaMedicoesPendentesAsync(ByVal Usuario As String)
            Me.ContaMedicoesPendentesAsync(Usuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ContaMedicoesPendentesAsync(ByVal Usuario As String, ByVal userState As Object)
            If (Me.ContaMedicoesPendentesOperationCompleted Is Nothing) Then
                Me.ContaMedicoesPendentesOperationCompleted = AddressOf Me.OnContaMedicoesPendentesOperationCompleted
            End If
            Me.InvokeAsync("ContaMedicoesPendentes", New Object() {Usuario}, Me.ContaMedicoesPendentesOperationCompleted, userState)
        End Sub
        
        Private Sub OnContaMedicoesPendentesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ContaMedicoesPendentesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ContaMedicoesPendentesCompleted(Me, New ContaMedicoesPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/ConsultaMedicoesPendentes", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaMedicoesPendentes(ByVal Usuario As String, ByVal limit As Integer, ByVal whereClausule As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaMedicoesPendentes", New Object() {Usuario, limit, whereClausule})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaMedicoesPendentesAsync(ByVal Usuario As String, ByVal limit As Integer, ByVal whereClausule As String)
            Me.ConsultaMedicoesPendentesAsync(Usuario, limit, whereClausule, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaMedicoesPendentesAsync(ByVal Usuario As String, ByVal limit As Integer, ByVal whereClausule As String, ByVal userState As Object)
            If (Me.ConsultaMedicoesPendentesOperationCompleted Is Nothing) Then
                Me.ConsultaMedicoesPendentesOperationCompleted = AddressOf Me.OnConsultaMedicoesPendentesOperationCompleted
            End If
            Me.InvokeAsync("ConsultaMedicoesPendentes", New Object() {Usuario, limit, whereClausule}, Me.ConsultaMedicoesPendentesOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaMedicoesPendentesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaMedicoesPendentesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaMedicoesPendentesCompleted(Me, New ConsultaMedicoesPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/ConsultaItensMedicoesPendentes", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaItensMedicoesPendentes(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaItensMedicoesPendentes", New Object() {Empresa, Contrato, CodMedicao})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaItensMedicoesPendentesAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String)
            Me.ConsultaItensMedicoesPendentesAsync(Empresa, Contrato, CodMedicao, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaItensMedicoesPendentesAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal userState As Object)
            If (Me.ConsultaItensMedicoesPendentesOperationCompleted Is Nothing) Then
                Me.ConsultaItensMedicoesPendentesOperationCompleted = AddressOf Me.OnConsultaItensMedicoesPendentesOperationCompleted
            End If
            Me.InvokeAsync("ConsultaItensMedicoesPendentes", New Object() {Empresa, Contrato, CodMedicao}, Me.ConsultaItensMedicoesPendentesOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaItensMedicoesPendentesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaItensMedicoesPendentesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaItensMedicoesPendentesCompleted(Me, New ConsultaItensMedicoesPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/ConsultaAprovacaoMedicao", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaAprovacaoMedicao(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaAprovacaoMedicao", New Object() {Empresa, Contrato, CodMedicao})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaAprovacaoMedicaoAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String)
            Me.ConsultaAprovacaoMedicaoAsync(Empresa, Contrato, CodMedicao, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaAprovacaoMedicaoAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal userState As Object)
            If (Me.ConsultaAprovacaoMedicaoOperationCompleted Is Nothing) Then
                Me.ConsultaAprovacaoMedicaoOperationCompleted = AddressOf Me.OnConsultaAprovacaoMedicaoOperationCompleted
            End If
            Me.InvokeAsync("ConsultaAprovacaoMedicao", New Object() {Empresa, Contrato, CodMedicao}, Me.ConsultaAprovacaoMedicaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaAprovacaoMedicaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaAprovacaoMedicaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaAprovacaoMedicaoCompleted(Me, New ConsultaAprovacaoMedicaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/AprovaMedicao", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AprovaMedicao(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal Usuario As String, ByVal Obra As String) As ResultadoExecucao
            Dim results() As Object = Me.Invoke("AprovaMedicao", New Object() {Empresa, Contrato, CodMedicao, Usuario, Obra})
            Return CType(results(0),ResultadoExecucao)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AprovaMedicaoAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal Usuario As String, ByVal Obra As String)
            Me.AprovaMedicaoAsync(Empresa, Contrato, CodMedicao, Usuario, Obra, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AprovaMedicaoAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal Usuario As String, ByVal Obra As String, ByVal userState As Object)
            If (Me.AprovaMedicaoOperationCompleted Is Nothing) Then
                Me.AprovaMedicaoOperationCompleted = AddressOf Me.OnAprovaMedicaoOperationCompleted
            End If
            Me.InvokeAsync("AprovaMedicao", New Object() {Empresa, Contrato, CodMedicao, Usuario, Obra}, Me.AprovaMedicaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAprovaMedicaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AprovaMedicaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AprovaMedicaoCompleted(Me, New AprovaMedicaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/ValidaAprovacaoMedicao", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidaAprovacaoMedicao(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal Usuario As String, ByVal Obra As String) As ResultadoExecucao
            Dim results() As Object = Me.Invoke("ValidaAprovacaoMedicao", New Object() {Empresa, Contrato, CodMedicao, Usuario, Obra})
            Return CType(results(0),ResultadoExecucao)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidaAprovacaoMedicaoAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal Usuario As String, ByVal Obra As String)
            Me.ValidaAprovacaoMedicaoAsync(Empresa, Contrato, CodMedicao, Usuario, Obra, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidaAprovacaoMedicaoAsync(ByVal Empresa As Integer, ByVal Contrato As String, ByVal CodMedicao As String, ByVal Usuario As String, ByVal Obra As String, ByVal userState As Object)
            If (Me.ValidaAprovacaoMedicaoOperationCompleted Is Nothing) Then
                Me.ValidaAprovacaoMedicaoOperationCompleted = AddressOf Me.OnValidaAprovacaoMedicaoOperationCompleted
            End If
            Me.InvokeAsync("ValidaAprovacaoMedicao", New Object() {Empresa, Contrato, CodMedicao, Usuario, Obra}, Me.ValidaAprovacaoMedicaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidaAprovacaoMedicaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidaAprovacaoMedicaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidaAprovacaoMedicaoCompleted(Me, New ValidaAprovacaoMedicaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/UAUTitanium")>  _
    Partial Public Class ResultadoExecucao
        
        Private tipoField As TipoMensagemResultadoExecucao
        
        Private sucessoField As Boolean
        
        Private mensagemField As String
        
        Private continuaField As Boolean
        
        '''<remarks/>
        Public Property Tipo() As TipoMensagemResultadoExecucao
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sucesso() As Boolean
            Get
                Return Me.sucessoField
            End Get
            Set
                Me.sucessoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Continua() As Boolean
            Get
                Return Me.continuaField
            End Get
            Set
                Me.continuaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/UAUTitanium")>  _
    Public Enum TipoMensagemResultadoExecucao
        
        '''<remarks/>
        Informativa
        
        '''<remarks/>
        Confirmacao
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ContaMedicoesPendentesCompletedEventHandler(ByVal sender As Object, ByVal e As ContaMedicoesPendentesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ContaMedicoesPendentesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultaMedicoesPendentesCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaMedicoesPendentesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaMedicoesPendentesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultaItensMedicoesPendentesCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaItensMedicoesPendentesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaItensMedicoesPendentesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultaAprovacaoMedicaoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaAprovacaoMedicaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaAprovacaoMedicaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AprovaMedicaoCompletedEventHandler(ByVal sender As Object, ByVal e As AprovaMedicaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AprovaMedicaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoExecucao
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoExecucao)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ValidaAprovacaoMedicaoCompletedEventHandler(ByVal sender As Object, ByVal e As ValidaAprovacaoMedicaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidaAprovacaoMedicaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoExecucao
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoExecucao)
            End Get
        End Property
    End Class
End Namespace
