'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsMobileReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsMobileSoap", [Namespace]:="http://tempuri.org/UAUTitanium")>  _
    Partial Public Class wsMobile
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getHospedagemMobileWebAPIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GravaLogErroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_wsMobileReference_wsMobile
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getHospedagemMobileWebAPICompleted As getHospedagemMobileWebAPICompletedEventHandler
        
        '''<remarks/>
        Public Event GravaLogErroCompleted As GravaLogErroCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/getHospedagemMobileWebAPI", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getHospedagemMobileWebAPI() As String
            Dim results() As Object = Me.Invoke("getHospedagemMobileWebAPI", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getHospedagemMobileWebAPIAsync()
            Me.getHospedagemMobileWebAPIAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getHospedagemMobileWebAPIAsync(ByVal userState As Object)
            If (Me.getHospedagemMobileWebAPIOperationCompleted Is Nothing) Then
                Me.getHospedagemMobileWebAPIOperationCompleted = AddressOf Me.OngetHospedagemMobileWebAPIOperationCompleted
            End If
            Me.InvokeAsync("getHospedagemMobileWebAPI", New Object(-1) {}, Me.getHospedagemMobileWebAPIOperationCompleted, userState)
        End Sub
        
        Private Sub OngetHospedagemMobileWebAPIOperationCompleted(ByVal arg As Object)
            If (Not (Me.getHospedagemMobileWebAPICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getHospedagemMobileWebAPICompleted(Me, New getHospedagemMobileWebAPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/GravaLogErro", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GravaLogErro(ByVal descricao As String, ByVal classe As String, ByVal metodo As String, ByVal os As String, ByVal aplicativo As String, ByVal versao As String, ByVal atividade As String)
            Me.Invoke("GravaLogErro", New Object() {descricao, classe, metodo, os, aplicativo, versao, atividade})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GravaLogErroAsync(ByVal descricao As String, ByVal classe As String, ByVal metodo As String, ByVal os As String, ByVal aplicativo As String, ByVal versao As String, ByVal atividade As String)
            Me.GravaLogErroAsync(descricao, classe, metodo, os, aplicativo, versao, atividade, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GravaLogErroAsync(ByVal descricao As String, ByVal classe As String, ByVal metodo As String, ByVal os As String, ByVal aplicativo As String, ByVal versao As String, ByVal atividade As String, ByVal userState As Object)
            If (Me.GravaLogErroOperationCompleted Is Nothing) Then
                Me.GravaLogErroOperationCompleted = AddressOf Me.OnGravaLogErroOperationCompleted
            End If
            Me.InvokeAsync("GravaLogErro", New Object() {descricao, classe, metodo, os, aplicativo, versao, atividade}, Me.GravaLogErroOperationCompleted, userState)
        End Sub
        
        Private Sub OnGravaLogErroOperationCompleted(ByVal arg As Object)
            If (Not (Me.GravaLogErroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GravaLogErroCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub getHospedagemMobileWebAPICompletedEventHandler(ByVal sender As Object, ByVal e As getHospedagemMobileWebAPICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getHospedagemMobileWebAPICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GravaLogErroCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
