'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace segurancaReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SegurancaSoap", [Namespace]:="http://tempuri.org/PortalUAU_WS/Seguranca")>  _
    Partial Public Class Seguranca
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ticketAutorizacaoValueField As TicketAutorizacao
        
        Private ChecarPermissaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChecarPermissaoMobOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChecarPermissaoObraOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaObrasUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarObrasEmpresasPorUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarObrasPorUsuarioEmpresaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SenhaUsuarioExpiradaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DiasRestantesExpiraSenhaUsrOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InativarUsuarioPorSenhaErradaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarSenhaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_segurancaReference_Seguranca
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property TicketAutorizacaoValue() As TicketAutorizacao
            Get
                Return Me.ticketAutorizacaoValueField
            End Get
            Set
                Me.ticketAutorizacaoValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ChecarPermissaoCompleted As ChecarPermissaoCompletedEventHandler
        
        '''<remarks/>
        Public Event ChecarPermissaoMobCompleted As ChecarPermissaoMobCompletedEventHandler
        
        '''<remarks/>
        Public Event ChecarPermissaoObraCompleted As ChecarPermissaoObraCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaObrasUsuarioCompleted As BuscaObrasUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarObrasEmpresasPorUsuarioCompleted As ConsultarObrasEmpresasPorUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarObrasPorUsuarioEmpresaCompleted As ConsultarObrasPorUsuarioEmpresaCompletedEventHandler
        
        '''<remarks/>
        Public Event SenhaUsuarioExpiradaCompleted As SenhaUsuarioExpiradaCompletedEventHandler
        
        '''<remarks/>
        Public Event DiasRestantesExpiraSenhaUsrCompleted As DiasRestantesExpiraSenhaUsrCompletedEventHandler
        
        '''<remarks/>
        Public Event InativarUsuarioPorSenhaErradaCompleted As InativarUsuarioPorSenhaErradaCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarSenhaCompleted As AlterarSenhaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TicketAutorizacaoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/ChecarPermissao", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChecarPermissao(ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU) As Boolean
            Dim results() As Object = Me.Invoke("ChecarPermissao", New Object() {Programa, PermissaoSolicitada})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChecarPermissaoAsync(ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU)
            Me.ChecarPermissaoAsync(Programa, PermissaoSolicitada, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChecarPermissaoAsync(ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU, ByVal userState As Object)
            If (Me.ChecarPermissaoOperationCompleted Is Nothing) Then
                Me.ChecarPermissaoOperationCompleted = AddressOf Me.OnChecarPermissaoOperationCompleted
            End If
            Me.InvokeAsync("ChecarPermissao", New Object() {Programa, PermissaoSolicitada}, Me.ChecarPermissaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnChecarPermissaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChecarPermissaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChecarPermissaoCompleted(Me, New ChecarPermissaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/ChecarPermissaoMob", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChecarPermissaoMob(ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU, ByVal usuario As String) As Boolean
            Dim results() As Object = Me.Invoke("ChecarPermissaoMob", New Object() {Programa, PermissaoSolicitada, usuario})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChecarPermissaoMobAsync(ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU, ByVal usuario As String)
            Me.ChecarPermissaoMobAsync(Programa, PermissaoSolicitada, usuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChecarPermissaoMobAsync(ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU, ByVal usuario As String, ByVal userState As Object)
            If (Me.ChecarPermissaoMobOperationCompleted Is Nothing) Then
                Me.ChecarPermissaoMobOperationCompleted = AddressOf Me.OnChecarPermissaoMobOperationCompleted
            End If
            Me.InvokeAsync("ChecarPermissaoMob", New Object() {Programa, PermissaoSolicitada, usuario}, Me.ChecarPermissaoMobOperationCompleted, userState)
        End Sub
        
        Private Sub OnChecarPermissaoMobOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChecarPermissaoMobCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChecarPermissaoMobCompleted(Me, New ChecarPermissaoMobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TicketAutorizacaoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/ChecarPermissaoObra", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChecarPermissaoObra(ByVal Empresa As Short, ByVal obra As String, ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU) As Boolean
            Dim results() As Object = Me.Invoke("ChecarPermissaoObra", New Object() {Empresa, obra, Programa, PermissaoSolicitada})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChecarPermissaoObraAsync(ByVal Empresa As Short, ByVal obra As String, ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU)
            Me.ChecarPermissaoObraAsync(Empresa, obra, Programa, PermissaoSolicitada, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChecarPermissaoObraAsync(ByVal Empresa As Short, ByVal obra As String, ByVal Programa As String, ByVal PermissaoSolicitada As EnumPermissaoUAU, ByVal userState As Object)
            If (Me.ChecarPermissaoObraOperationCompleted Is Nothing) Then
                Me.ChecarPermissaoObraOperationCompleted = AddressOf Me.OnChecarPermissaoObraOperationCompleted
            End If
            Me.InvokeAsync("ChecarPermissaoObra", New Object() {Empresa, obra, Programa, PermissaoSolicitada}, Me.ChecarPermissaoObraOperationCompleted, userState)
        End Sub
        
        Private Sub OnChecarPermissaoObraOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChecarPermissaoObraCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChecarPermissaoObraCompleted(Me, New ChecarPermissaoObraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TicketAutorizacaoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/BuscaObrasUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaObrasUsuario() As String
            Dim results() As Object = Me.Invoke("BuscaObrasUsuario", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaObrasUsuarioAsync()
            Me.BuscaObrasUsuarioAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaObrasUsuarioAsync(ByVal userState As Object)
            If (Me.BuscaObrasUsuarioOperationCompleted Is Nothing) Then
                Me.BuscaObrasUsuarioOperationCompleted = AddressOf Me.OnBuscaObrasUsuarioOperationCompleted
            End If
            Me.InvokeAsync("BuscaObrasUsuario", New Object(-1) {}, Me.BuscaObrasUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaObrasUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaObrasUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaObrasUsuarioCompleted(Me, New BuscaObrasUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/ConsultarObrasEmpresasPorUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarObrasEmpresasPorUsuario(ByVal strLoginUsuario As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarObrasEmpresasPorUsuario", New Object() {strLoginUsuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarObrasEmpresasPorUsuarioAsync(ByVal strLoginUsuario As String)
            Me.ConsultarObrasEmpresasPorUsuarioAsync(strLoginUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarObrasEmpresasPorUsuarioAsync(ByVal strLoginUsuario As String, ByVal userState As Object)
            If (Me.ConsultarObrasEmpresasPorUsuarioOperationCompleted Is Nothing) Then
                Me.ConsultarObrasEmpresasPorUsuarioOperationCompleted = AddressOf Me.OnConsultarObrasEmpresasPorUsuarioOperationCompleted
            End If
            Me.InvokeAsync("ConsultarObrasEmpresasPorUsuario", New Object() {strLoginUsuario}, Me.ConsultarObrasEmpresasPorUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarObrasEmpresasPorUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarObrasEmpresasPorUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarObrasEmpresasPorUsuarioCompleted(Me, New ConsultarObrasEmpresasPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/ConsultarObrasPorUsuarioEmpresa", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarObrasPorUsuarioEmpresa(ByVal Usuario As String, ByVal Empresa As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarObrasPorUsuarioEmpresa", New Object() {Usuario, Empresa})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarObrasPorUsuarioEmpresaAsync(ByVal Usuario As String, ByVal Empresa As Integer)
            Me.ConsultarObrasPorUsuarioEmpresaAsync(Usuario, Empresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarObrasPorUsuarioEmpresaAsync(ByVal Usuario As String, ByVal Empresa As Integer, ByVal userState As Object)
            If (Me.ConsultarObrasPorUsuarioEmpresaOperationCompleted Is Nothing) Then
                Me.ConsultarObrasPorUsuarioEmpresaOperationCompleted = AddressOf Me.OnConsultarObrasPorUsuarioEmpresaOperationCompleted
            End If
            Me.InvokeAsync("ConsultarObrasPorUsuarioEmpresa", New Object() {Usuario, Empresa}, Me.ConsultarObrasPorUsuarioEmpresaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarObrasPorUsuarioEmpresaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarObrasPorUsuarioEmpresaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarObrasPorUsuarioEmpresaCompleted(Me, New ConsultarObrasPorUsuarioEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/SenhaUsuarioExpirada", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SenhaUsuarioExpirada(ByVal strUsuario As String) As Boolean
            Dim results() As Object = Me.Invoke("SenhaUsuarioExpirada", New Object() {strUsuario})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SenhaUsuarioExpiradaAsync(ByVal strUsuario As String)
            Me.SenhaUsuarioExpiradaAsync(strUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SenhaUsuarioExpiradaAsync(ByVal strUsuario As String, ByVal userState As Object)
            If (Me.SenhaUsuarioExpiradaOperationCompleted Is Nothing) Then
                Me.SenhaUsuarioExpiradaOperationCompleted = AddressOf Me.OnSenhaUsuarioExpiradaOperationCompleted
            End If
            Me.InvokeAsync("SenhaUsuarioExpirada", New Object() {strUsuario}, Me.SenhaUsuarioExpiradaOperationCompleted, userState)
        End Sub
        
        Private Sub OnSenhaUsuarioExpiradaOperationCompleted(ByVal arg As Object)
            If (Not (Me.SenhaUsuarioExpiradaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SenhaUsuarioExpiradaCompleted(Me, New SenhaUsuarioExpiradaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/DiasRestantesExpiraSenhaUsr", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DiasRestantesExpiraSenhaUsr(ByVal strUsuario As String) As Integer
            Dim results() As Object = Me.Invoke("DiasRestantesExpiraSenhaUsr", New Object() {strUsuario})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DiasRestantesExpiraSenhaUsrAsync(ByVal strUsuario As String)
            Me.DiasRestantesExpiraSenhaUsrAsync(strUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DiasRestantesExpiraSenhaUsrAsync(ByVal strUsuario As String, ByVal userState As Object)
            If (Me.DiasRestantesExpiraSenhaUsrOperationCompleted Is Nothing) Then
                Me.DiasRestantesExpiraSenhaUsrOperationCompleted = AddressOf Me.OnDiasRestantesExpiraSenhaUsrOperationCompleted
            End If
            Me.InvokeAsync("DiasRestantesExpiraSenhaUsr", New Object() {strUsuario}, Me.DiasRestantesExpiraSenhaUsrOperationCompleted, userState)
        End Sub
        
        Private Sub OnDiasRestantesExpiraSenhaUsrOperationCompleted(ByVal arg As Object)
            If (Not (Me.DiasRestantesExpiraSenhaUsrCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DiasRestantesExpiraSenhaUsrCompleted(Me, New DiasRestantesExpiraSenhaUsrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/InativarUsuarioPorSenhaErrada", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub InativarUsuarioPorSenhaErrada(ByVal strUsuario As String)
            Me.Invoke("InativarUsuarioPorSenhaErrada", New Object() {strUsuario})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InativarUsuarioPorSenhaErradaAsync(ByVal strUsuario As String)
            Me.InativarUsuarioPorSenhaErradaAsync(strUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InativarUsuarioPorSenhaErradaAsync(ByVal strUsuario As String, ByVal userState As Object)
            If (Me.InativarUsuarioPorSenhaErradaOperationCompleted Is Nothing) Then
                Me.InativarUsuarioPorSenhaErradaOperationCompleted = AddressOf Me.OnInativarUsuarioPorSenhaErradaOperationCompleted
            End If
            Me.InvokeAsync("InativarUsuarioPorSenhaErrada", New Object() {strUsuario}, Me.InativarUsuarioPorSenhaErradaOperationCompleted, userState)
        End Sub
        
        Private Sub OnInativarUsuarioPorSenhaErradaOperationCompleted(ByVal arg As Object)
            If (Not (Me.InativarUsuarioPorSenhaErradaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InativarUsuarioPorSenhaErradaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/Seguranca/AlterarSenha", RequestNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/Seguranca", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AlterarSenha(ByVal strUsuario As String, ByVal strSenha As String, ByVal strSenhaCriptografada As String)
            Me.Invoke("AlterarSenha", New Object() {strUsuario, strSenha, strSenhaCriptografada})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarSenhaAsync(ByVal strUsuario As String, ByVal strSenha As String, ByVal strSenhaCriptografada As String)
            Me.AlterarSenhaAsync(strUsuario, strSenha, strSenhaCriptografada, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarSenhaAsync(ByVal strUsuario As String, ByVal strSenha As String, ByVal strSenhaCriptografada As String, ByVal userState As Object)
            If (Me.AlterarSenhaOperationCompleted Is Nothing) Then
                Me.AlterarSenhaOperationCompleted = AddressOf Me.OnAlterarSenhaOperationCompleted
            End If
            Me.InvokeAsync("AlterarSenha", New Object() {strUsuario, strSenha, strSenhaCriptografada}, Me.AlterarSenhaOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarSenhaOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarSenhaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarSenhaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/Seguranca"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/Seguranca", IsNullable:=false)>  _
    Partial Public Class TicketAutorizacao
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private ticketField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Ticket() As String
            Get
                Return Me.ticketField
            End Get
            Set
                Me.ticketField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/Seguranca")>  _
    Public Enum EnumPermissaoUAU
        
        '''<remarks/>
        SemValorAtribuido
        
        '''<remarks/>
        SemAcesso
        
        '''<remarks/>
        Consulta
        
        '''<remarks/>
        Emissao
        
        '''<remarks/>
        Inclusao
        
        '''<remarks/>
        Alteracao
        
        '''<remarks/>
        Exclusao
        
        '''<remarks/>
        Autorizacao_Aprovacao
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ChecarPermissaoCompletedEventHandler(ByVal sender As Object, ByVal e As ChecarPermissaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChecarPermissaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ChecarPermissaoMobCompletedEventHandler(ByVal sender As Object, ByVal e As ChecarPermissaoMobCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChecarPermissaoMobCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ChecarPermissaoObraCompletedEventHandler(ByVal sender As Object, ByVal e As ChecarPermissaoObraCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChecarPermissaoObraCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub BuscaObrasUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaObrasUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaObrasUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarObrasEmpresasPorUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarObrasEmpresasPorUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarObrasEmpresasPorUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarObrasPorUsuarioEmpresaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarObrasPorUsuarioEmpresaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarObrasPorUsuarioEmpresaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub SenhaUsuarioExpiradaCompletedEventHandler(ByVal sender As Object, ByVal e As SenhaUsuarioExpiradaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SenhaUsuarioExpiradaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub DiasRestantesExpiraSenhaUsrCompletedEventHandler(ByVal sender As Object, ByVal e As DiasRestantesExpiraSenhaUsrCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DiasRestantesExpiraSenhaUsrCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub InativarUsuarioPorSenhaErradaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AlterarSenhaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
