'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace ProcessoPagamentoReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProcessoPagamentoSoap", [Namespace]:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento")>  _
    Partial Public Class ProcessoPagamento
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarProcessosPagamentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarFaixaValorUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarProcessoPagamentoVOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarItensProcessosPagamentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarProcessoPagamentoObservacaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarTodosDepartamentosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarDepartamentosUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarProcessoPagamentoDepartamentoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarAprovacaoEmissaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarProcessoEmissaoPagamentoResumidoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ContaProcessoEmissaoPagamentoResumidoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidarAprovacaoProcessoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AprovarProcessoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_ProcessoPagamentoReference_ProcessoPagamento
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarProcessosPagamentoCompleted As ConsultarProcessosPagamentoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarFaixaValorUsuarioCompleted As ConsultarFaixaValorUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarProcessoPagamentoVCompleted As AlterarProcessoPagamentoVCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarItensProcessosPagamentoCompleted As ConsultarItensProcessosPagamentoCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarProcessoPagamentoObservacaoCompleted As AlterarProcessoPagamentoObservacaoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarTodosDepartamentosCompleted As ConsultarTodosDepartamentosCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarDepartamentosUsuarioCompleted As ConsultarDepartamentosUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarProcessoPagamentoDepartamentoCompleted As AlterarProcessoPagamentoDepartamentoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarAprovacaoEmissaoCompleted As ConsultarAprovacaoEmissaoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarProcessoEmissaoPagamentoResumidoCompleted As ConsultarProcessoEmissaoPagamentoResumidoCompletedEventHandler
        
        '''<remarks/>
        Public Event ContaProcessoEmissaoPagamentoResumidoCompleted As ContaProcessoEmissaoPagamentoResumidoCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidarAprovacaoProcessoCompleted As ValidarAprovacaoProcessoCompletedEventHandler
        
        '''<remarks/>
        Public Event AprovarProcessoCompleted As AprovarProcessoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarProcessosPagamento", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarProcessosPagamento(ByVal empresaObra As String, ByVal periodoInicio As Date, ByVal periodoFim As Date, ByVal mostrarProcessosAssistentePagamento As Boolean, ByVal mostrarProcessosPagamentoAAprovar As Boolean, ByVal numeroDepartamento As String, ByVal valorInicial As Double, ByVal valorFinal As Double) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarProcessosPagamento", New Object() {empresaObra, periodoInicio, periodoFim, mostrarProcessosAssistentePagamento, mostrarProcessosPagamentoAAprovar, numeroDepartamento, valorInicial, valorFinal})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarProcessosPagamentoAsync(ByVal empresaObra As String, ByVal periodoInicio As Date, ByVal periodoFim As Date, ByVal mostrarProcessosAssistentePagamento As Boolean, ByVal mostrarProcessosPagamentoAAprovar As Boolean, ByVal numeroDepartamento As String, ByVal valorInicial As Double, ByVal valorFinal As Double)
            Me.ConsultarProcessosPagamentoAsync(empresaObra, periodoInicio, periodoFim, mostrarProcessosAssistentePagamento, mostrarProcessosPagamentoAAprovar, numeroDepartamento, valorInicial, valorFinal, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarProcessosPagamentoAsync(ByVal empresaObra As String, ByVal periodoInicio As Date, ByVal periodoFim As Date, ByVal mostrarProcessosAssistentePagamento As Boolean, ByVal mostrarProcessosPagamentoAAprovar As Boolean, ByVal numeroDepartamento As String, ByVal valorInicial As Double, ByVal valorFinal As Double, ByVal userState As Object)
            If (Me.ConsultarProcessosPagamentoOperationCompleted Is Nothing) Then
                Me.ConsultarProcessosPagamentoOperationCompleted = AddressOf Me.OnConsultarProcessosPagamentoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarProcessosPagamento", New Object() {empresaObra, periodoInicio, periodoFim, mostrarProcessosAssistentePagamento, mostrarProcessosPagamentoAAprovar, numeroDepartamento, valorInicial, valorFinal}, Me.ConsultarProcessosPagamentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarProcessosPagamentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarProcessosPagamentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarProcessosPagamentoCompleted(Me, New ConsultarProcessosPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarFaixaValorUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarFaixaValorUsuario() As Double()
            Dim results() As Object = Me.Invoke("ConsultarFaixaValorUsuario", New Object(-1) {})
            Return CType(results(0),Double())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarFaixaValorUsuarioAsync()
            Me.ConsultarFaixaValorUsuarioAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarFaixaValorUsuarioAsync(ByVal userState As Object)
            If (Me.ConsultarFaixaValorUsuarioOperationCompleted Is Nothing) Then
                Me.ConsultarFaixaValorUsuarioOperationCompleted = AddressOf Me.OnConsultarFaixaValorUsuarioOperationCompleted
            End If
            Me.InvokeAsync("ConsultarFaixaValorUsuario", New Object(-1) {}, Me.ConsultarFaixaValorUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarFaixaValorUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarFaixaValorUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarFaixaValorUsuarioCompleted(Me, New ConsultarFaixaValorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/AlterarProcessoPagamentoV", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlterarProcessoPagamentoV(ByVal processosPagamentosAAprovar() As parametrosProcessoPagamento) As retornoProcQueNaoForamConfirmados()
            Dim results() As Object = Me.Invoke("AlterarProcessoPagamentoV", New Object() {processosPagamentosAAprovar})
            Return CType(results(0),retornoProcQueNaoForamConfirmados())
        End Function
        
        '''<remarks/>
        Public Overloads Sub AlterarProcessoPagamentoVAsync(ByVal processosPagamentosAAprovar() As parametrosProcessoPagamento)
            Me.AlterarProcessoPagamentoVAsync(processosPagamentosAAprovar, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarProcessoPagamentoVAsync(ByVal processosPagamentosAAprovar() As parametrosProcessoPagamento, ByVal userState As Object)
            If (Me.AlterarProcessoPagamentoVOperationCompleted Is Nothing) Then
                Me.AlterarProcessoPagamentoVOperationCompleted = AddressOf Me.OnAlterarProcessoPagamentoVOperationCompleted
            End If
            Me.InvokeAsync("AlterarProcessoPagamentoV", New Object() {processosPagamentosAAprovar}, Me.AlterarProcessoPagamentoVOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarProcessoPagamentoVOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarProcessoPagamentoVCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarProcessoPagamentoVCompleted(Me, New AlterarProcessoPagamentoVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarItensProcessosPagament"& _ 
            "o", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarItensProcessosPagamento(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal codigoContrato As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarItensProcessosPagamento", New Object() {codigoEmpresa, codigoObra, numeroProcesso, codigoContrato})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarItensProcessosPagamentoAsync(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal codigoContrato As Integer)
            Me.ConsultarItensProcessosPagamentoAsync(codigoEmpresa, codigoObra, numeroProcesso, codigoContrato, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarItensProcessosPagamentoAsync(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal codigoContrato As Integer, ByVal userState As Object)
            If (Me.ConsultarItensProcessosPagamentoOperationCompleted Is Nothing) Then
                Me.ConsultarItensProcessosPagamentoOperationCompleted = AddressOf Me.OnConsultarItensProcessosPagamentoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarItensProcessosPagamento", New Object() {codigoEmpresa, codigoObra, numeroProcesso, codigoContrato}, Me.ConsultarItensProcessosPagamentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarItensProcessosPagamentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarItensProcessosPagamentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarItensProcessosPagamentoCompleted(Me, New ConsultarItensProcessosPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/AlterarProcessoPagamentoObserva"& _ 
            "cao", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlterarProcessoPagamentoObservacao(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal numeroParcela As Integer, ByVal observacao As String) As Boolean
            Dim results() As Object = Me.Invoke("AlterarProcessoPagamentoObservacao", New Object() {codigoEmpresa, codigoObra, numeroProcesso, numeroParcela, observacao})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AlterarProcessoPagamentoObservacaoAsync(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal numeroParcela As Integer, ByVal observacao As String)
            Me.AlterarProcessoPagamentoObservacaoAsync(codigoEmpresa, codigoObra, numeroProcesso, numeroParcela, observacao, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarProcessoPagamentoObservacaoAsync(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal numeroParcela As Integer, ByVal observacao As String, ByVal userState As Object)
            If (Me.AlterarProcessoPagamentoObservacaoOperationCompleted Is Nothing) Then
                Me.AlterarProcessoPagamentoObservacaoOperationCompleted = AddressOf Me.OnAlterarProcessoPagamentoObservacaoOperationCompleted
            End If
            Me.InvokeAsync("AlterarProcessoPagamentoObservacao", New Object() {codigoEmpresa, codigoObra, numeroProcesso, numeroParcela, observacao}, Me.AlterarProcessoPagamentoObservacaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarProcessoPagamentoObservacaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarProcessoPagamentoObservacaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarProcessoPagamentoObservacaoCompleted(Me, New AlterarProcessoPagamentoObservacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarTodosDepartamentos", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarTodosDepartamentos() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarTodosDepartamentos", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarTodosDepartamentosAsync()
            Me.ConsultarTodosDepartamentosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarTodosDepartamentosAsync(ByVal userState As Object)
            If (Me.ConsultarTodosDepartamentosOperationCompleted Is Nothing) Then
                Me.ConsultarTodosDepartamentosOperationCompleted = AddressOf Me.OnConsultarTodosDepartamentosOperationCompleted
            End If
            Me.InvokeAsync("ConsultarTodosDepartamentos", New Object(-1) {}, Me.ConsultarTodosDepartamentosOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarTodosDepartamentosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarTodosDepartamentosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarTodosDepartamentosCompleted(Me, New ConsultarTodosDepartamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarDepartamentosUsuario", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarDepartamentosUsuario() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarDepartamentosUsuario", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarDepartamentosUsuarioAsync()
            Me.ConsultarDepartamentosUsuarioAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarDepartamentosUsuarioAsync(ByVal userState As Object)
            If (Me.ConsultarDepartamentosUsuarioOperationCompleted Is Nothing) Then
                Me.ConsultarDepartamentosUsuarioOperationCompleted = AddressOf Me.OnConsultarDepartamentosUsuarioOperationCompleted
            End If
            Me.InvokeAsync("ConsultarDepartamentosUsuario", New Object(-1) {}, Me.ConsultarDepartamentosUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarDepartamentosUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarDepartamentosUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarDepartamentosUsuarioCompleted(Me, New ConsultarDepartamentosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/AlterarProcessoPagamentoDeparta"& _ 
            "mento", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlterarProcessoPagamentoDepartamento(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal codigoDepartamento As String) As Boolean
            Dim results() As Object = Me.Invoke("AlterarProcessoPagamentoDepartamento", New Object() {codigoEmpresa, codigoObra, numeroProcesso, codigoDepartamento})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AlterarProcessoPagamentoDepartamentoAsync(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal codigoDepartamento As String)
            Me.AlterarProcessoPagamentoDepartamentoAsync(codigoEmpresa, codigoObra, numeroProcesso, codigoDepartamento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarProcessoPagamentoDepartamentoAsync(ByVal codigoEmpresa As Integer, ByVal codigoObra As String, ByVal numeroProcesso As Integer, ByVal codigoDepartamento As String, ByVal userState As Object)
            If (Me.AlterarProcessoPagamentoDepartamentoOperationCompleted Is Nothing) Then
                Me.AlterarProcessoPagamentoDepartamentoOperationCompleted = AddressOf Me.OnAlterarProcessoPagamentoDepartamentoOperationCompleted
            End If
            Me.InvokeAsync("AlterarProcessoPagamentoDepartamento", New Object() {codigoEmpresa, codigoObra, numeroProcesso, codigoDepartamento}, Me.AlterarProcessoPagamentoDepartamentoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarProcessoPagamentoDepartamentoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarProcessoPagamentoDepartamentoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarProcessoPagamentoDepartamentoCompleted(Me, New AlterarProcessoPagamentoDepartamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarAprovacaoEmissao", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarAprovacaoEmissao(ByVal numeroProcesso As Integer, ByVal numeroParcela As Integer, ByVal Obra As String, ByVal empresa As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarAprovacaoEmissao", New Object() {numeroProcesso, numeroParcela, Obra, empresa})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarAprovacaoEmissaoAsync(ByVal numeroProcesso As Integer, ByVal numeroParcela As Integer, ByVal Obra As String, ByVal empresa As Integer)
            Me.ConsultarAprovacaoEmissaoAsync(numeroProcesso, numeroParcela, Obra, empresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarAprovacaoEmissaoAsync(ByVal numeroProcesso As Integer, ByVal numeroParcela As Integer, ByVal Obra As String, ByVal empresa As Integer, ByVal userState As Object)
            If (Me.ConsultarAprovacaoEmissaoOperationCompleted Is Nothing) Then
                Me.ConsultarAprovacaoEmissaoOperationCompleted = AddressOf Me.OnConsultarAprovacaoEmissaoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarAprovacaoEmissao", New Object() {numeroProcesso, numeroParcela, Obra, empresa}, Me.ConsultarAprovacaoEmissaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarAprovacaoEmissaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarAprovacaoEmissaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarAprovacaoEmissaoCompleted(Me, New ConsultarAprovacaoEmissaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ConsultarProcessoEmissaoPagamen"& _ 
            "toResumido", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarProcessoEmissaoPagamentoResumido(ByVal loginUsuario As String, ByVal limit As Integer, ByVal whereClausule As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarProcessoEmissaoPagamentoResumido", New Object() {loginUsuario, limit, whereClausule})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarProcessoEmissaoPagamentoResumidoAsync(ByVal loginUsuario As String, ByVal limit As Integer, ByVal whereClausule As String)
            Me.ConsultarProcessoEmissaoPagamentoResumidoAsync(loginUsuario, limit, whereClausule, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarProcessoEmissaoPagamentoResumidoAsync(ByVal loginUsuario As String, ByVal limit As Integer, ByVal whereClausule As String, ByVal userState As Object)
            If (Me.ConsultarProcessoEmissaoPagamentoResumidoOperationCompleted Is Nothing) Then
                Me.ConsultarProcessoEmissaoPagamentoResumidoOperationCompleted = AddressOf Me.OnConsultarProcessoEmissaoPagamentoResumidoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarProcessoEmissaoPagamentoResumido", New Object() {loginUsuario, limit, whereClausule}, Me.ConsultarProcessoEmissaoPagamentoResumidoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarProcessoEmissaoPagamentoResumidoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarProcessoEmissaoPagamentoResumidoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarProcessoEmissaoPagamentoResumidoCompleted(Me, New ConsultarProcessoEmissaoPagamentoResumidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ContaProcessoEmissaoPagamentoRe"& _ 
            "sumido", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ContaProcessoEmissaoPagamentoResumido(ByVal loginUsuario As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ContaProcessoEmissaoPagamentoResumido", New Object() {loginUsuario})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ContaProcessoEmissaoPagamentoResumidoAsync(ByVal loginUsuario As String)
            Me.ContaProcessoEmissaoPagamentoResumidoAsync(loginUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ContaProcessoEmissaoPagamentoResumidoAsync(ByVal loginUsuario As String, ByVal userState As Object)
            If (Me.ContaProcessoEmissaoPagamentoResumidoOperationCompleted Is Nothing) Then
                Me.ContaProcessoEmissaoPagamentoResumidoOperationCompleted = AddressOf Me.OnContaProcessoEmissaoPagamentoResumidoOperationCompleted
            End If
            Me.InvokeAsync("ContaProcessoEmissaoPagamentoResumido", New Object() {loginUsuario}, Me.ContaProcessoEmissaoPagamentoResumidoOperationCompleted, userState)
        End Sub
        
        Private Sub OnContaProcessoEmissaoPagamentoResumidoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ContaProcessoEmissaoPagamentoResumidoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ContaProcessoEmissaoPagamentoResumidoCompleted(Me, New ContaProcessoEmissaoPagamentoResumidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/ValidarAprovacaoProcesso", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidarAprovacaoProcesso(ByVal codEmpresa As Integer, ByVal codObra As String, ByVal numeroProcesso As String, ByVal numeroParcela As String, ByVal tipoProcesso As Integer, ByVal loginUsuario As String, ByVal aprovarProcesso As StatusAprovacaoProcesso) As ResultadoExecucao
            Dim results() As Object = Me.Invoke("ValidarAprovacaoProcesso", New Object() {codEmpresa, codObra, numeroProcesso, numeroParcela, tipoProcesso, loginUsuario, aprovarProcesso})
            Return CType(results(0),ResultadoExecucao)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidarAprovacaoProcessoAsync(ByVal codEmpresa As Integer, ByVal codObra As String, ByVal numeroProcesso As String, ByVal numeroParcela As String, ByVal tipoProcesso As Integer, ByVal loginUsuario As String, ByVal aprovarProcesso As StatusAprovacaoProcesso)
            Me.ValidarAprovacaoProcessoAsync(codEmpresa, codObra, numeroProcesso, numeroParcela, tipoProcesso, loginUsuario, aprovarProcesso, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidarAprovacaoProcessoAsync(ByVal codEmpresa As Integer, ByVal codObra As String, ByVal numeroProcesso As String, ByVal numeroParcela As String, ByVal tipoProcesso As Integer, ByVal loginUsuario As String, ByVal aprovarProcesso As StatusAprovacaoProcesso, ByVal userState As Object)
            If (Me.ValidarAprovacaoProcessoOperationCompleted Is Nothing) Then
                Me.ValidarAprovacaoProcessoOperationCompleted = AddressOf Me.OnValidarAprovacaoProcessoOperationCompleted
            End If
            Me.InvokeAsync("ValidarAprovacaoProcesso", New Object() {codEmpresa, codObra, numeroProcesso, numeroParcela, tipoProcesso, loginUsuario, aprovarProcesso}, Me.ValidarAprovacaoProcessoOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidarAprovacaoProcessoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidarAprovacaoProcessoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidarAprovacaoProcessoCompleted(Me, New ValidarAprovacaoProcessoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PortalUAU_WS/ProcessoPagamento/AprovarProcesso", RequestNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", ResponseNamespace:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AprovarProcesso(ByVal codEmpresa As Integer, ByVal codObra As String, ByVal numeroProcesso As String, ByVal numeroParcela As String, ByVal tipoProcesso As Integer, ByVal aprovarOProcesso As StatusAprovacaoProcesso, ByVal loginUsuario As String) As ResultadoExecucao
            Dim results() As Object = Me.Invoke("AprovarProcesso", New Object() {codEmpresa, codObra, numeroProcesso, numeroParcela, tipoProcesso, aprovarOProcesso, loginUsuario})
            Return CType(results(0),ResultadoExecucao)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AprovarProcessoAsync(ByVal codEmpresa As Integer, ByVal codObra As String, ByVal numeroProcesso As String, ByVal numeroParcela As String, ByVal tipoProcesso As Integer, ByVal aprovarOProcesso As StatusAprovacaoProcesso, ByVal loginUsuario As String)
            Me.AprovarProcessoAsync(codEmpresa, codObra, numeroProcesso, numeroParcela, tipoProcesso, aprovarOProcesso, loginUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AprovarProcessoAsync(ByVal codEmpresa As Integer, ByVal codObra As String, ByVal numeroProcesso As String, ByVal numeroParcela As String, ByVal tipoProcesso As Integer, ByVal aprovarOProcesso As StatusAprovacaoProcesso, ByVal loginUsuario As String, ByVal userState As Object)
            If (Me.AprovarProcessoOperationCompleted Is Nothing) Then
                Me.AprovarProcessoOperationCompleted = AddressOf Me.OnAprovarProcessoOperationCompleted
            End If
            Me.InvokeAsync("AprovarProcesso", New Object() {codEmpresa, codObra, numeroProcesso, numeroParcela, tipoProcesso, aprovarOProcesso, loginUsuario}, Me.AprovarProcessoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAprovarProcessoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AprovarProcessoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AprovarProcessoCompleted(Me, New AprovarProcessoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento")>  _
    Partial Public Class parametrosProcessoPagamento
        
        Private codigoEmpresaValueField As Integer
        
        Private codigoObraValueField As String
        
        Private numeroParcelaValueField As Integer
        
        Private numeroProcessoValueField As Integer
        
        Private confirmarAprovacaoValueField As Boolean
        
        Private codigoDepartamentoValueField As String
        
        '''<remarks/>
        Public Property codigoEmpresaValue() As Integer
            Get
                Return Me.codigoEmpresaValueField
            End Get
            Set
                Me.codigoEmpresaValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigoObraValue() As String
            Get
                Return Me.codigoObraValueField
            End Get
            Set
                Me.codigoObraValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroParcelaValue() As Integer
            Get
                Return Me.numeroParcelaValueField
            End Get
            Set
                Me.numeroParcelaValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroProcessoValue() As Integer
            Get
                Return Me.numeroProcessoValueField
            End Get
            Set
                Me.numeroProcessoValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property confirmarAprovacaoValue() As Boolean
            Get
                Return Me.confirmarAprovacaoValueField
            End Get
            Set
                Me.confirmarAprovacaoValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigoDepartamentoValue() As String
            Get
                Return Me.codigoDepartamentoValueField
            End Get
            Set
                Me.codigoDepartamentoValueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento")>  _
    Partial Public Class ResultadoExecucao
        
        Private tipoField As TipoMensagemResultadoExecucao
        
        Private sucessoField As Boolean
        
        Private mensagemField As String
        
        Private continuaField As Boolean
        
        '''<remarks/>
        Public Property Tipo() As TipoMensagemResultadoExecucao
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sucesso() As Boolean
            Get
                Return Me.sucessoField
            End Get
            Set
                Me.sucessoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Continua() As Boolean
            Get
                Return Me.continuaField
            End Get
            Set
                Me.continuaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento")>  _
    Public Enum TipoMensagemResultadoExecucao
        
        '''<remarks/>
        Informativa
        
        '''<remarks/>
        Confirmacao
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento")>  _
    Partial Public Class retornoProcQueNaoForamConfirmados
        
        Private codigoEmpresaValueField As Integer
        
        Private codigoObraValueField As String
        
        Private numeroProcessoValueField As Integer
        
        Private confirmarAprovacaoValueField As Boolean
        
        Private mensagemInconsistenciaField As String
        
        '''<remarks/>
        Public Property codigoEmpresaValue() As Integer
            Get
                Return Me.codigoEmpresaValueField
            End Get
            Set
                Me.codigoEmpresaValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigoObraValue() As String
            Get
                Return Me.codigoObraValueField
            End Get
            Set
                Me.codigoObraValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroProcessoValue() As Integer
            Get
                Return Me.numeroProcessoValueField
            End Get
            Set
                Me.numeroProcessoValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property confirmarAprovacaoValue() As Boolean
            Get
                Return Me.confirmarAprovacaoValueField
            End Get
            Set
                Me.confirmarAprovacaoValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensagemInconsistencia() As String
            Get
                Return Me.mensagemInconsistenciaField
            End Get
            Set
                Me.mensagemInconsistenciaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/PortalUAU_WS/ProcessoPagamento")>  _
    Public Enum StatusAprovacaoProcesso
        
        '''<remarks/>
        Sim
        
        '''<remarks/>
        Nao
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarProcessosPagamentoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarProcessosPagamentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarProcessosPagamentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarFaixaValorUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarFaixaValorUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarFaixaValorUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AlterarProcessoPagamentoVCompletedEventHandler(ByVal sender As Object, ByVal e As AlterarProcessoPagamentoVCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AlterarProcessoPagamentoVCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As retornoProcQueNaoForamConfirmados()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),retornoProcQueNaoForamConfirmados())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarItensProcessosPagamentoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarItensProcessosPagamentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarItensProcessosPagamentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AlterarProcessoPagamentoObservacaoCompletedEventHandler(ByVal sender As Object, ByVal e As AlterarProcessoPagamentoObservacaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AlterarProcessoPagamentoObservacaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarTodosDepartamentosCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarTodosDepartamentosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarTodosDepartamentosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarDepartamentosUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarDepartamentosUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarDepartamentosUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AlterarProcessoPagamentoDepartamentoCompletedEventHandler(ByVal sender As Object, ByVal e As AlterarProcessoPagamentoDepartamentoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AlterarProcessoPagamentoDepartamentoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarAprovacaoEmissaoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarAprovacaoEmissaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarAprovacaoEmissaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarProcessoEmissaoPagamentoResumidoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarProcessoEmissaoPagamentoResumidoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarProcessoEmissaoPagamentoResumidoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ContaProcessoEmissaoPagamentoResumidoCompletedEventHandler(ByVal sender As Object, ByVal e As ContaProcessoEmissaoPagamentoResumidoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ContaProcessoEmissaoPagamentoResumidoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ValidarAprovacaoProcessoCompletedEventHandler(ByVal sender As Object, ByVal e As ValidarAprovacaoProcessoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidarAprovacaoProcessoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoExecucao
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoExecucao)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AprovarProcessoCompletedEventHandler(ByVal sender As Object, ByVal e As AprovarProcessoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AprovarProcessoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoExecucao
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoExecucao)
            End Get
        End Property
    End Class
End Namespace
