'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsEmpresaProdReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsRegistroUauSoap", [Namespace]:="http://tempuri.org/SuporteNet_site/wsRegistroUau")>  _
    Partial Public Class wsRegistroUau
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarPelaChaveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InserirOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeletarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarChaveRegistroPorEmpresaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InativarRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GravarChaveRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarChavePorEmpresaTipoBancoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarChavePorChaveInicialOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarAutomaticamenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CriptografarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DescriptografarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DelimitadorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RenovarRegistroAutomaticamenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BuscaNomeEmpresaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarDadosConfPortalUauPorCodigoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarDadosConfPortalUauPorTokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GeraTokenEmpresaPorCodigoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_wsEmpresaProdReference_wsRegistroUau
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarPelaChaveCompleted As ConsultarPelaChaveCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarCompleted As ConsultarCompletedEventHandler
        
        '''<remarks/>
        Public Event InserirCompleted As InserirCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarCompleted As AlterarCompletedEventHandler
        
        '''<remarks/>
        Public Event DeletarCompleted As DeletarCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarChaveRegistroPorEmpresaCompleted As ConsultarChaveRegistroPorEmpresaCompletedEventHandler
        
        '''<remarks/>
        Public Event InativarRegistroCompleted As InativarRegistroCompletedEventHandler
        
        '''<remarks/>
        Public Event GravarChaveRegistroCompleted As GravarChaveRegistroCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarChavePorEmpresaTipoBancoCompleted As ConsultarChavePorEmpresaTipoBancoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarChavePorChaveInicialCompleted As ConsultarChavePorChaveInicialCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarAutomaticamenteCompleted As RegistrarAutomaticamenteCompletedEventHandler
        
        '''<remarks/>
        Public Event CriptografarCompleted As CriptografarCompletedEventHandler
        
        '''<remarks/>
        Public Event DescriptografarCompleted As DescriptografarCompletedEventHandler
        
        '''<remarks/>
        Public Event DelimitadorCompleted As DelimitadorCompletedEventHandler
        
        '''<remarks/>
        Public Event RenovarRegistroAutomaticamenteCompleted As RenovarRegistroAutomaticamenteCompletedEventHandler
        
        '''<remarks/>
        Public Event BuscaNomeEmpresaCompleted As BuscaNomeEmpresaCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarDadosConfPortalUauPorCodigoCompleted As ConsultarDadosConfPortalUauPorCodigoCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarDadosConfPortalUauPorTokenCompleted As ConsultarDadosConfPortalUauPorTokenCompletedEventHandler
        
        '''<remarks/>
        Public Event GeraTokenEmpresaPorCodigoCompleted As GeraTokenEmpresaPorCodigoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/ConsultarPelaChave", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarPelaChave(ByVal Num_reg As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarPelaChave", New Object() {Num_reg})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarPelaChaveAsync(ByVal Num_reg As Integer)
            Me.ConsultarPelaChaveAsync(Num_reg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarPelaChaveAsync(ByVal Num_reg As Integer, ByVal userState As Object)
            If (Me.ConsultarPelaChaveOperationCompleted Is Nothing) Then
                Me.ConsultarPelaChaveOperationCompleted = AddressOf Me.OnConsultarPelaChaveOperationCompleted
            End If
            Me.InvokeAsync("ConsultarPelaChave", New Object() {Num_reg}, Me.ConsultarPelaChaveOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarPelaChaveOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarPelaChaveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarPelaChaveCompleted(Me, New ConsultarPelaChaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Consultar", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Consultar() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Consultar", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarAsync()
            Me.ConsultarAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarAsync(ByVal userState As Object)
            If (Me.ConsultarOperationCompleted Is Nothing) Then
                Me.ConsultarOperationCompleted = AddressOf Me.OnConsultarOperationCompleted
            End If
            Me.InvokeAsync("Consultar", New Object(-1) {}, Me.ConsultarOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarCompleted(Me, New ConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Inserir", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Inserir(ByVal objInfo As _ChavesRegistroInfo)
            Me.Invoke("Inserir", New Object() {objInfo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InserirAsync(ByVal objInfo As _ChavesRegistroInfo)
            Me.InserirAsync(objInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InserirAsync(ByVal objInfo As _ChavesRegistroInfo, ByVal userState As Object)
            If (Me.InserirOperationCompleted Is Nothing) Then
                Me.InserirOperationCompleted = AddressOf Me.OnInserirOperationCompleted
            End If
            Me.InvokeAsync("Inserir", New Object() {objInfo}, Me.InserirOperationCompleted, userState)
        End Sub
        
        Private Sub OnInserirOperationCompleted(ByVal arg As Object)
            If (Not (Me.InserirCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InserirCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Alterar", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Alterar(ByVal ObjInfo As _ChavesRegistroInfo)
            Me.Invoke("Alterar", New Object() {ObjInfo})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarAsync(ByVal ObjInfo As _ChavesRegistroInfo)
            Me.AlterarAsync(ObjInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarAsync(ByVal ObjInfo As _ChavesRegistroInfo, ByVal userState As Object)
            If (Me.AlterarOperationCompleted Is Nothing) Then
                Me.AlterarOperationCompleted = AddressOf Me.OnAlterarOperationCompleted
            End If
            Me.InvokeAsync("Alterar", New Object() {ObjInfo}, Me.AlterarOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Deletar", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Deletar(ByVal Num_reg As Integer) As Boolean
            Dim results() As Object = Me.Invoke("Deletar", New Object() {Num_reg})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeletarAsync(ByVal Num_reg As Integer)
            Me.DeletarAsync(Num_reg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeletarAsync(ByVal Num_reg As Integer, ByVal userState As Object)
            If (Me.DeletarOperationCompleted Is Nothing) Then
                Me.DeletarOperationCompleted = AddressOf Me.OnDeletarOperationCompleted
            End If
            Me.InvokeAsync("Deletar", New Object() {Num_reg}, Me.DeletarOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeletarOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeletarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeletarCompleted(Me, New DeletarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/ConsultarChaveRegistroPorEmpresa"& _ 
            "", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarChaveRegistroPorEmpresa(ByVal NumEmpresa As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultarChaveRegistroPorEmpresa", New Object() {NumEmpresa})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarChaveRegistroPorEmpresaAsync(ByVal NumEmpresa As Integer)
            Me.ConsultarChaveRegistroPorEmpresaAsync(NumEmpresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarChaveRegistroPorEmpresaAsync(ByVal NumEmpresa As Integer, ByVal userState As Object)
            If (Me.ConsultarChaveRegistroPorEmpresaOperationCompleted Is Nothing) Then
                Me.ConsultarChaveRegistroPorEmpresaOperationCompleted = AddressOf Me.OnConsultarChaveRegistroPorEmpresaOperationCompleted
            End If
            Me.InvokeAsync("ConsultarChaveRegistroPorEmpresa", New Object() {NumEmpresa}, Me.ConsultarChaveRegistroPorEmpresaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarChaveRegistroPorEmpresaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarChaveRegistroPorEmpresaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarChaveRegistroPorEmpresaCompleted(Me, New ConsultarChaveRegistroPorEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/InativarRegistro", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub InativarRegistro(ByVal NumRegistro As Integer, ByVal UsrInat As String)
            Me.Invoke("InativarRegistro", New Object() {NumRegistro, UsrInat})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InativarRegistroAsync(ByVal NumRegistro As Integer, ByVal UsrInat As String)
            Me.InativarRegistroAsync(NumRegistro, UsrInat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InativarRegistroAsync(ByVal NumRegistro As Integer, ByVal UsrInat As String, ByVal userState As Object)
            If (Me.InativarRegistroOperationCompleted Is Nothing) Then
                Me.InativarRegistroOperationCompleted = AddressOf Me.OnInativarRegistroOperationCompleted
            End If
            Me.InvokeAsync("InativarRegistro", New Object() {NumRegistro, UsrInat}, Me.InativarRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnInativarRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.InativarRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InativarRegistroCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/GravarChaveRegistro", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GravarChaveRegistro(ByVal InfoChaveRegistro As _ChavesRegistroInfo)
            Me.Invoke("GravarChaveRegistro", New Object() {InfoChaveRegistro})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GravarChaveRegistroAsync(ByVal InfoChaveRegistro As _ChavesRegistroInfo)
            Me.GravarChaveRegistroAsync(InfoChaveRegistro, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GravarChaveRegistroAsync(ByVal InfoChaveRegistro As _ChavesRegistroInfo, ByVal userState As Object)
            If (Me.GravarChaveRegistroOperationCompleted Is Nothing) Then
                Me.GravarChaveRegistroOperationCompleted = AddressOf Me.OnGravarChaveRegistroOperationCompleted
            End If
            Me.InvokeAsync("GravarChaveRegistro", New Object() {InfoChaveRegistro}, Me.GravarChaveRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnGravarChaveRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.GravarChaveRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GravarChaveRegistroCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/ConsultarChavePorEmpresaTipoBanc"& _ 
            "o", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarChavePorEmpresaTipoBanco(ByVal NumEmpresa As Integer, ByVal TipoBanco As Char) As _ChavesRegistroInfo
            Dim results() As Object = Me.Invoke("ConsultarChavePorEmpresaTipoBanco", New Object() {NumEmpresa, TipoBanco})
            Return CType(results(0),_ChavesRegistroInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarChavePorEmpresaTipoBancoAsync(ByVal NumEmpresa As Integer, ByVal TipoBanco As Char)
            Me.ConsultarChavePorEmpresaTipoBancoAsync(NumEmpresa, TipoBanco, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarChavePorEmpresaTipoBancoAsync(ByVal NumEmpresa As Integer, ByVal TipoBanco As Char, ByVal userState As Object)
            If (Me.ConsultarChavePorEmpresaTipoBancoOperationCompleted Is Nothing) Then
                Me.ConsultarChavePorEmpresaTipoBancoOperationCompleted = AddressOf Me.OnConsultarChavePorEmpresaTipoBancoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarChavePorEmpresaTipoBanco", New Object() {NumEmpresa, TipoBanco}, Me.ConsultarChavePorEmpresaTipoBancoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarChavePorEmpresaTipoBancoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarChavePorEmpresaTipoBancoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarChavePorEmpresaTipoBancoCompleted(Me, New ConsultarChavePorEmpresaTipoBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/ConsultarChavePorChaveInicial", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarChavePorChaveInicial(ByVal ChaveInicial As String) As _ChavesRegistroInfo
            Dim results() As Object = Me.Invoke("ConsultarChavePorChaveInicial", New Object() {ChaveInicial})
            Return CType(results(0),_ChavesRegistroInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarChavePorChaveInicialAsync(ByVal ChaveInicial As String)
            Me.ConsultarChavePorChaveInicialAsync(ChaveInicial, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarChavePorChaveInicialAsync(ByVal ChaveInicial As String, ByVal userState As Object)
            If (Me.ConsultarChavePorChaveInicialOperationCompleted Is Nothing) Then
                Me.ConsultarChavePorChaveInicialOperationCompleted = AddressOf Me.OnConsultarChavePorChaveInicialOperationCompleted
            End If
            Me.InvokeAsync("ConsultarChavePorChaveInicial", New Object() {ChaveInicial}, Me.ConsultarChavePorChaveInicialOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarChavePorChaveInicialOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarChavePorChaveInicialCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarChavePorChaveInicialCompleted(Me, New ConsultarChavePorChaveInicialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/RegistrarAutomaticamente", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarAutomaticamente(ByVal InfoChaveReg As _ChavesRegInfo) As String
            Dim results() As Object = Me.Invoke("RegistrarAutomaticamente", New Object() {InfoChaveReg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarAutomaticamenteAsync(ByVal InfoChaveReg As _ChavesRegInfo)
            Me.RegistrarAutomaticamenteAsync(InfoChaveReg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarAutomaticamenteAsync(ByVal InfoChaveReg As _ChavesRegInfo, ByVal userState As Object)
            If (Me.RegistrarAutomaticamenteOperationCompleted Is Nothing) Then
                Me.RegistrarAutomaticamenteOperationCompleted = AddressOf Me.OnRegistrarAutomaticamenteOperationCompleted
            End If
            Me.InvokeAsync("RegistrarAutomaticamente", New Object() {InfoChaveReg}, Me.RegistrarAutomaticamenteOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarAutomaticamenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarAutomaticamenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarAutomaticamenteCompleted(Me, New RegistrarAutomaticamenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Criptografar", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Criptografar(ByVal InfoChaveReg As _ChavesRegInfo) As _ChavesRegInfo
            Dim results() As Object = Me.Invoke("Criptografar", New Object() {InfoChaveReg})
            Return CType(results(0),_ChavesRegInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CriptografarAsync(ByVal InfoChaveReg As _ChavesRegInfo)
            Me.CriptografarAsync(InfoChaveReg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CriptografarAsync(ByVal InfoChaveReg As _ChavesRegInfo, ByVal userState As Object)
            If (Me.CriptografarOperationCompleted Is Nothing) Then
                Me.CriptografarOperationCompleted = AddressOf Me.OnCriptografarOperationCompleted
            End If
            Me.InvokeAsync("Criptografar", New Object() {InfoChaveReg}, Me.CriptografarOperationCompleted, userState)
        End Sub
        
        Private Sub OnCriptografarOperationCompleted(ByVal arg As Object)
            If (Not (Me.CriptografarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CriptografarCompleted(Me, New CriptografarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Descriptografar", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Descriptografar(ByVal InfoChaveReg As _ChavesRegInfo) As _ChavesRegInfo
            Dim results() As Object = Me.Invoke("Descriptografar", New Object() {InfoChaveReg})
            Return CType(results(0),_ChavesRegInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DescriptografarAsync(ByVal InfoChaveReg As _ChavesRegInfo)
            Me.DescriptografarAsync(InfoChaveReg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DescriptografarAsync(ByVal InfoChaveReg As _ChavesRegInfo, ByVal userState As Object)
            If (Me.DescriptografarOperationCompleted Is Nothing) Then
                Me.DescriptografarOperationCompleted = AddressOf Me.OnDescriptografarOperationCompleted
            End If
            Me.InvokeAsync("Descriptografar", New Object() {InfoChaveReg}, Me.DescriptografarOperationCompleted, userState)
        End Sub
        
        Private Sub OnDescriptografarOperationCompleted(ByVal arg As Object)
            If (Not (Me.DescriptografarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DescriptografarCompleted(Me, New DescriptografarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/Delimitador", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delimitador() As String
            Dim results() As Object = Me.Invoke("Delimitador", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DelimitadorAsync()
            Me.DelimitadorAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DelimitadorAsync(ByVal userState As Object)
            If (Me.DelimitadorOperationCompleted Is Nothing) Then
                Me.DelimitadorOperationCompleted = AddressOf Me.OnDelimitadorOperationCompleted
            End If
            Me.InvokeAsync("Delimitador", New Object(-1) {}, Me.DelimitadorOperationCompleted, userState)
        End Sub
        
        Private Sub OnDelimitadorOperationCompleted(ByVal arg As Object)
            If (Not (Me.DelimitadorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DelimitadorCompleted(Me, New DelimitadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/RenovarRegistroAutomaticamente", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RenovarRegistroAutomaticamente(ByVal InfoChaveReg As _ChavesRegInfo, ByVal ChaveCriptografada As String) As _ChavesRegInfo
            Dim results() As Object = Me.Invoke("RenovarRegistroAutomaticamente", New Object() {InfoChaveReg, ChaveCriptografada})
            Return CType(results(0),_ChavesRegInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RenovarRegistroAutomaticamenteAsync(ByVal InfoChaveReg As _ChavesRegInfo, ByVal ChaveCriptografada As String)
            Me.RenovarRegistroAutomaticamenteAsync(InfoChaveReg, ChaveCriptografada, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RenovarRegistroAutomaticamenteAsync(ByVal InfoChaveReg As _ChavesRegInfo, ByVal ChaveCriptografada As String, ByVal userState As Object)
            If (Me.RenovarRegistroAutomaticamenteOperationCompleted Is Nothing) Then
                Me.RenovarRegistroAutomaticamenteOperationCompleted = AddressOf Me.OnRenovarRegistroAutomaticamenteOperationCompleted
            End If
            Me.InvokeAsync("RenovarRegistroAutomaticamente", New Object() {InfoChaveReg, ChaveCriptografada}, Me.RenovarRegistroAutomaticamenteOperationCompleted, userState)
        End Sub
        
        Private Sub OnRenovarRegistroAutomaticamenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.RenovarRegistroAutomaticamenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RenovarRegistroAutomaticamenteCompleted(Me, New RenovarRegistroAutomaticamenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/BuscaNomeEmpresa", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BuscaNomeEmpresa(ByVal Numemp As Integer) As String
            Dim results() As Object = Me.Invoke("BuscaNomeEmpresa", New Object() {Numemp})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BuscaNomeEmpresaAsync(ByVal Numemp As Integer)
            Me.BuscaNomeEmpresaAsync(Numemp, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BuscaNomeEmpresaAsync(ByVal Numemp As Integer, ByVal userState As Object)
            If (Me.BuscaNomeEmpresaOperationCompleted Is Nothing) Then
                Me.BuscaNomeEmpresaOperationCompleted = AddressOf Me.OnBuscaNomeEmpresaOperationCompleted
            End If
            Me.InvokeAsync("BuscaNomeEmpresa", New Object() {Numemp}, Me.BuscaNomeEmpresaOperationCompleted, userState)
        End Sub
        
        Private Sub OnBuscaNomeEmpresaOperationCompleted(ByVal arg As Object)
            If (Not (Me.BuscaNomeEmpresaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BuscaNomeEmpresaCompleted(Me, New BuscaNomeEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/ConsultarDadosConfPortalUauPorCo"& _ 
            "digo", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarDadosConfPortalUauPorCodigo(ByVal codEmpresa As Integer) As _ConfPortalUAUInfo
            Dim results() As Object = Me.Invoke("ConsultarDadosConfPortalUauPorCodigo", New Object() {codEmpresa})
            Return CType(results(0),_ConfPortalUAUInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarDadosConfPortalUauPorCodigoAsync(ByVal codEmpresa As Integer)
            Me.ConsultarDadosConfPortalUauPorCodigoAsync(codEmpresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarDadosConfPortalUauPorCodigoAsync(ByVal codEmpresa As Integer, ByVal userState As Object)
            If (Me.ConsultarDadosConfPortalUauPorCodigoOperationCompleted Is Nothing) Then
                Me.ConsultarDadosConfPortalUauPorCodigoOperationCompleted = AddressOf Me.OnConsultarDadosConfPortalUauPorCodigoOperationCompleted
            End If
            Me.InvokeAsync("ConsultarDadosConfPortalUauPorCodigo", New Object() {codEmpresa}, Me.ConsultarDadosConfPortalUauPorCodigoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarDadosConfPortalUauPorCodigoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarDadosConfPortalUauPorCodigoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarDadosConfPortalUauPorCodigoCompleted(Me, New ConsultarDadosConfPortalUauPorCodigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/ConsultarDadosConfPortalUauPorTo"& _ 
            "ken", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarDadosConfPortalUauPorToken(ByVal token As String) As String
            Dim results() As Object = Me.Invoke("ConsultarDadosConfPortalUauPorToken", New Object() {token})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarDadosConfPortalUauPorTokenAsync(ByVal token As String)
            Me.ConsultarDadosConfPortalUauPorTokenAsync(token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarDadosConfPortalUauPorTokenAsync(ByVal token As String, ByVal userState As Object)
            If (Me.ConsultarDadosConfPortalUauPorTokenOperationCompleted Is Nothing) Then
                Me.ConsultarDadosConfPortalUauPorTokenOperationCompleted = AddressOf Me.OnConsultarDadosConfPortalUauPorTokenOperationCompleted
            End If
            Me.InvokeAsync("ConsultarDadosConfPortalUauPorToken", New Object() {token}, Me.ConsultarDadosConfPortalUauPorTokenOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarDadosConfPortalUauPorTokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarDadosConfPortalUauPorTokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarDadosConfPortalUauPorTokenCompleted(Me, New ConsultarDadosConfPortalUauPorTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuporteNet_site/wsRegistroUau/GeraTokenEmpresaPorCodigo", RequestNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", ResponseNamespace:="http://tempuri.org/SuporteNet_site/wsRegistroUau", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GeraTokenEmpresaPorCodigo(ByVal codEmpresa As Integer) As String
            Dim results() As Object = Me.Invoke("GeraTokenEmpresaPorCodigo", New Object() {codEmpresa})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GeraTokenEmpresaPorCodigoAsync(ByVal codEmpresa As Integer)
            Me.GeraTokenEmpresaPorCodigoAsync(codEmpresa, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GeraTokenEmpresaPorCodigoAsync(ByVal codEmpresa As Integer, ByVal userState As Object)
            If (Me.GeraTokenEmpresaPorCodigoOperationCompleted Is Nothing) Then
                Me.GeraTokenEmpresaPorCodigoOperationCompleted = AddressOf Me.OnGeraTokenEmpresaPorCodigoOperationCompleted
            End If
            Me.InvokeAsync("GeraTokenEmpresaPorCodigo", New Object() {codEmpresa}, Me.GeraTokenEmpresaPorCodigoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGeraTokenEmpresaPorCodigoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GeraTokenEmpresaPorCodigoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GeraTokenEmpresaPorCodigoCompleted(Me, New GeraTokenEmpresaPorCodigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/SuporteNET_WS/WsChavesRegistro")>  _
    Partial Public Class _ChavesRegistroInfo
        
        Private num_regField As Integer
        
        Private numEmp_regField As Integer
        
        Private chave_regField As String
        
        Private tipoBanco_regField As String
        
        Private dataExpiracao_regField As Date
        
        Private dataCad_regField As Date
        
        Private usrCad_regField As String
        
        Private atInat_regField As Byte
        
        Private dataInat_regField As Date
        
        Private usrInat_regField As String
        
        '''<remarks/>
        Public Property Num_reg() As Integer
            Get
                Return Me.num_regField
            End Get
            Set
                Me.num_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumEmp_reg() As Integer
            Get
                Return Me.numEmp_regField
            End Get
            Set
                Me.numEmp_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Chave_reg() As String
            Get
                Return Me.chave_regField
            End Get
            Set
                Me.chave_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoBanco_reg() As String
            Get
                Return Me.tipoBanco_regField
            End Get
            Set
                Me.tipoBanco_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataExpiracao_reg() As Date
            Get
                Return Me.dataExpiracao_regField
            End Get
            Set
                Me.dataExpiracao_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataCad_reg() As Date
            Get
                Return Me.dataCad_regField
            End Get
            Set
                Me.dataCad_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsrCad_reg() As String
            Get
                Return Me.usrCad_regField
            End Get
            Set
                Me.usrCad_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AtInat_reg() As Byte
            Get
                Return Me.atInat_regField
            End Get
            Set
                Me.atInat_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataInat_reg() As Date
            Get
                Return Me.dataInat_regField
            End Get
            Set
                Me.dataInat_regField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsrInat_reg() As String
            Get
                Return Me.usrInat_regField
            End Get
            Set
                Me.usrInat_regField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/SuporteNET_WS/WsEmpresa")>  _
    Partial Public Class _ConfPortalUAUInfo
        
        Private numEmp_PWebField As Integer
        
        Private uRLWS_PWebField As String
        
        Private emailContato_PWebField As String
        
        Private empresaUAU_PWebField As Short
        
        Private obraUAU_PWebField As String
        
        Private usrCad_PWebField As String
        
        Private dataCad_PwebField As Date
        
        Private dataAlt_PwebField As Date
        
        Private usrAlt_PWebField As String
        
        Private atInat_PWebField As Byte
        
        Private descrPortalUAU_PWebField As String
        
        Private hTML_PWebField As String
        
        Private uRLPaginaCentro_PWebField As String
        
        Private numHospUauWeb_PWebField As Integer
        
        '''<remarks/>
        Public Property NumEmp_PWeb() As Integer
            Get
                Return Me.numEmp_PWebField
            End Get
            Set
                Me.numEmp_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property URLWS_PWeb() As String
            Get
                Return Me.uRLWS_PWebField
            End Get
            Set
                Me.uRLWS_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailContato_PWeb() As String
            Get
                Return Me.emailContato_PWebField
            End Get
            Set
                Me.emailContato_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmpresaUAU_PWeb() As Short
            Get
                Return Me.empresaUAU_PWebField
            End Get
            Set
                Me.empresaUAU_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObraUAU_PWeb() As String
            Get
                Return Me.obraUAU_PWebField
            End Get
            Set
                Me.obraUAU_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsrCad_PWeb() As String
            Get
                Return Me.usrCad_PWebField
            End Get
            Set
                Me.usrCad_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataCad_Pweb() As Date
            Get
                Return Me.dataCad_PwebField
            End Get
            Set
                Me.dataCad_PwebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAlt_Pweb() As Date
            Get
                Return Me.dataAlt_PwebField
            End Get
            Set
                Me.dataAlt_PwebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsrAlt_PWeb() As String
            Get
                Return Me.usrAlt_PWebField
            End Get
            Set
                Me.usrAlt_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AtInat_PWeb() As Byte
            Get
                Return Me.atInat_PWebField
            End Get
            Set
                Me.atInat_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescrPortalUAU_PWeb() As String
            Get
                Return Me.descrPortalUAU_PWebField
            End Get
            Set
                Me.descrPortalUAU_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HTML_PWeb() As String
            Get
                Return Me.hTML_PWebField
            End Get
            Set
                Me.hTML_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property URLPaginaCentro_PWeb() As String
            Get
                Return Me.uRLPaginaCentro_PWebField
            End Get
            Set
                Me.uRLPaginaCentro_PWebField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumHospUauWeb_PWeb() As Integer
            Get
                Return Me.numHospUauWeb_PWebField
            End Get
            Set
                Me.numHospUauWeb_PWebField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/SuporteNET_WS/WsChavesRegistro")>  _
    Partial Public Class _ChavesRegInfo
        
        Private numEmpresaField As String
        
        Private nomeServidorField As String
        
        Private nomeBancoDadosField As String
        
        Private tipoBancoField As String
        
        Private dataExpiracaoField As String
        
        Private dataCriacaoBDField As String
        
        Private statusField As String
        
        '''<remarks/>
        Public Property NumEmpresa() As String
            Get
                Return Me.numEmpresaField
            End Get
            Set
                Me.numEmpresaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeServidor() As String
            Get
                Return Me.nomeServidorField
            End Get
            Set
                Me.nomeServidorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeBancoDados() As String
            Get
                Return Me.nomeBancoDadosField
            End Get
            Set
                Me.nomeBancoDadosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoBanco() As String
            Get
                Return Me.tipoBancoField
            End Get
            Set
                Me.tipoBancoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataExpiracao() As String
            Get
                Return Me.dataExpiracaoField
            End Get
            Set
                Me.dataExpiracaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataCriacaoBD() As String
            Get
                Return Me.dataCriacaoBDField
            End Get
            Set
                Me.dataCriacaoBDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarPelaChaveCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarPelaChaveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarPelaChaveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub InserirCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub AlterarCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub DeletarCompletedEventHandler(ByVal sender As Object, ByVal e As DeletarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeletarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarChaveRegistroPorEmpresaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarChaveRegistroPorEmpresaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarChaveRegistroPorEmpresaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub InativarRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GravarChaveRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarChavePorEmpresaTipoBancoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarChavePorEmpresaTipoBancoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarChavePorEmpresaTipoBancoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ChavesRegistroInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ChavesRegistroInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarChavePorChaveInicialCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarChavePorChaveInicialCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarChavePorChaveInicialCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ChavesRegistroInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ChavesRegistroInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RegistrarAutomaticamenteCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarAutomaticamenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarAutomaticamenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub CriptografarCompletedEventHandler(ByVal sender As Object, ByVal e As CriptografarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CriptografarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ChavesRegInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ChavesRegInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub DescriptografarCompletedEventHandler(ByVal sender As Object, ByVal e As DescriptografarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DescriptografarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ChavesRegInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ChavesRegInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub DelimitadorCompletedEventHandler(ByVal sender As Object, ByVal e As DelimitadorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DelimitadorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RenovarRegistroAutomaticamenteCompletedEventHandler(ByVal sender As Object, ByVal e As RenovarRegistroAutomaticamenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RenovarRegistroAutomaticamenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ChavesRegInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ChavesRegInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub BuscaNomeEmpresaCompletedEventHandler(ByVal sender As Object, ByVal e As BuscaNomeEmpresaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BuscaNomeEmpresaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarDadosConfPortalUauPorCodigoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarDadosConfPortalUauPorCodigoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarDadosConfPortalUauPorCodigoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ConfPortalUAUInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ConfPortalUAUInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultarDadosConfPortalUauPorTokenCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarDadosConfPortalUauPorTokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarDadosConfPortalUauPorTokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GeraTokenEmpresaPorCodigoCompletedEventHandler(ByVal sender As Object, ByVal e As GeraTokenEmpresaPorCodigoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GeraTokenEmpresaPorCodigoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
