'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsBoletoReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsBoletoSoap", [Namespace]:="http://tempuri.org/UAUMobileWebAPI/wsBoleto")>  _
    Partial Public Class wsBoleto
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviaNotificacaoBoletoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AcessoACS.My.MySettings.Default.AcessoACS_wsBoletoReference_wsBoleto
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviaNotificacaoBoletoCompleted As EnviaNotificacaoBoletoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUMobileWebAPI/wsBoleto/EnviaNotificacaoBoleto", RequestNamespace:="http://tempuri.org/UAUMobileWebAPI/wsBoleto", ResponseNamespace:="http://tempuri.org/UAUMobileWebAPI/wsBoleto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub EnviaNotificacaoBoleto()
            Me.Invoke("EnviaNotificacaoBoleto", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviaNotificacaoBoletoAsync()
            Me.EnviaNotificacaoBoletoAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviaNotificacaoBoletoAsync(ByVal userState As Object)
            If (Me.EnviaNotificacaoBoletoOperationCompleted Is Nothing) Then
                Me.EnviaNotificacaoBoletoOperationCompleted = AddressOf Me.OnEnviaNotificacaoBoletoOperationCompleted
            End If
            Me.InvokeAsync("EnviaNotificacaoBoleto", New Object(-1) {}, Me.EnviaNotificacaoBoletoOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviaNotificacaoBoletoOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviaNotificacaoBoletoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviaNotificacaoBoletoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub EnviaNotificacaoBoletoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
