'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace wsHistoricoInsumoReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsHistoricoInsumoSoap", [Namespace]:="http://tempuri.org/UAUTitanium")>  _
    Partial Public Class wsHistoricoInsumo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultaHistoricoInsumoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UAUMobileWebAPI.My.MySettings.Default.UAUMobileWebAPI_wsHistoricoInsumoReference_wsHistoricoInsumo
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultaHistoricoInsumoCompleted As ConsultaHistoricoInsumoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UAUTitanium/ConsultaHistoricoInsumo", RequestNamespace:="http://tempuri.org/UAUTitanium", ResponseNamespace:="http://tempuri.org/UAUTitanium", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaHistoricoInsumo(ByVal codigoInsumo As String, ByVal naoMostraInsumoSemCotacao As Boolean, ByVal dataInicial As Date, ByVal dataFinal As Date, ByVal ordenar As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ConsultaHistoricoInsumo", New Object() {codigoInsumo, naoMostraInsumoSemCotacao, dataInicial, dataFinal, ordenar})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaHistoricoInsumoAsync(ByVal codigoInsumo As String, ByVal naoMostraInsumoSemCotacao As Boolean, ByVal dataInicial As Date, ByVal dataFinal As Date, ByVal ordenar As Boolean)
            Me.ConsultaHistoricoInsumoAsync(codigoInsumo, naoMostraInsumoSemCotacao, dataInicial, dataFinal, ordenar, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaHistoricoInsumoAsync(ByVal codigoInsumo As String, ByVal naoMostraInsumoSemCotacao As Boolean, ByVal dataInicial As Date, ByVal dataFinal As Date, ByVal ordenar As Boolean, ByVal userState As Object)
            If (Me.ConsultaHistoricoInsumoOperationCompleted Is Nothing) Then
                Me.ConsultaHistoricoInsumoOperationCompleted = AddressOf Me.OnConsultaHistoricoInsumoOperationCompleted
            End If
            Me.InvokeAsync("ConsultaHistoricoInsumo", New Object() {codigoInsumo, naoMostraInsumoSemCotacao, dataInicial, dataFinal, ordenar}, Me.ConsultaHistoricoInsumoOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaHistoricoInsumoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaHistoricoInsumoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaHistoricoInsumoCompleted(Me, New ConsultaHistoricoInsumoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ConsultaHistoricoInsumoCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaHistoricoInsumoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaHistoricoInsumoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
